CREATE TABLE "TFS"."SERVICEINSTRUCTION"
(
   SERVICEINSTRUCTIONID varchar(255) PRIMARY KEY NOT NULL,
   TYPE varchar(255),
   STATUS varchar(255),
   DETAILS long varchar,
   APPROVERS varchar(30),
   USERACTIVEDIRECTORYID varchar(255),
   CREATEDBY varchar(255),
   APPROVEDBY varchar(255),
   DATEAPPROVED timestamp,
   CREATEDDATE timestamp,
   MODIFIEDDATE timestamp,
   APPROVALCOUNT int
)
;
CREATE UNIQUE INDEX SQL121106152253850 ON "TFS"."SERVICEINSTRUCTION"(SERVICEINSTRUCTIONID)
;
