CREATE TABLE @facility@.LNTFEXP (
		AANO CHAR(20) DEFAULT ' ' NOT NULL,
		FCODE CHAR(3) DEFAULT ' ' NOT NULL,
		FSEQ DECIMAL(11 , 0) DEFAULT 0 NOT NULL,
		TRSEQ DECIMAL(5 , 0) DEFAULT 0 NOT NULL,
		RECSEQ DECIMAL(5 , 0) DEFAULT 0 NOT NULL,
		ERRFLD CHAR(10) DEFAULT ' ' NOT NULL,
		ERRDSC CHAR(80) DEFAULT ' ' NOT NULL,
		MDAT6 DECIMAL(6 , 0) DEFAULT 0 NOT NULL,
		MDAT7 DECIMAL(7 , 0) DEFAULT 0 NOT NULL,
		MTIME DECIMAL(6 , 0) DEFAULT 0 NOT NULL,
		USRID CHAR(10) DEFAULT ' ' NOT NULL
	);

--CREATE INDEX LNTFEXP ON LNTFEXP (AANO ASC, FCODE ASC, FSEQ ASC, TRSEQ ASC, RECSEQ ASC);

