CREATE TABLE "CUSTOMERACCOUNT"
(
   ID bigint PRIMARY KEY,
   ACCOUNT_NUMBER varchar(50),
   CUSTOMER_NUMBER varchar(50),
   DATE_CREATED timestamp
)
;
CREATE UNIQUE INDEX SQL121107161542720 ON "CUSTOMERACCOUNT"(ID)
;