ALTER TABLE CASATRANSACTIONLOG ADD TRADESERVICEID VARCHAR(36);
ALTER TABLE CASATRANSACTIONLOG DROP COLUMN SERVICETYPE;
ALTER TABLE CASATRANSACTIONLOG DROP COLUMN DOCUMENTTYPE;
ALTER TABLE CASATRANSACTIONLOG DROP COLUMN DOCUMENTCLASS;
ALTER TABLE CASATRANSACTIONLOG DROP COLUMN DOCUMENTSUBTYPE1;
ALTER TABLE CASATRANSACTIONLOG DROP COLUMN DOCUMENTSUBTYPE2;
