--<ScriptOptions statementTerminator="@"/>
CREATE TABLE TFSDB2S.GLIS_HAND_OFF_FILE(
    GLIS_ID VARCHAR(26) NOT NULL,
    COMPANY_NUMBER VARCHAR(4),
    ACCOUNT_NUMBER VARCHAR(50),
    UCPB_ACCOUNTING_CODE VARCHAR(100),
    UCPB_PARTICULARS VARCHAR(100),
    TRANSACTION_CODE CHAR(2),
    RESP_CTR_NUMBER VARCHAR(10),
    SOURCE_CODE VARCHAR(3),
    AMOUNT DECIMAL(15,2),
    PESOAMOUNT DECIMAL(15,2),
    DATE TIMESTAMP,
    REF_TRAN_SEQ_NUMBER VARCHAR(8),
    TRAN_DES_DOCUMENT_NUMBER VARCHAR(100),
    IS_POSTED CHAR(1) DEFAULT 'N' NOT NULL,
    IS_APPROVED CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_BY VARCHAR(20),
    MODIFIED_BY VARCHAR(20),
    APPROVED_BY VARCHAR(20),
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP,
    APPROVED_DATE TIMESTAMP,
    REMARKS VARCHAR(500),
    JLRFID SMALLINT,
    ACCENTRY_ID BIGINT,
    SYSTEM_START_TIME1 TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW BEGIN , 
    SYSTEM_END_TIME1 TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END , 
    TRANS_ID1 TIMESTAMP(12) GENERATED ALWAYS AS TRANSACTION START ID , 
    PERIOD SYSTEM_TIME("SYSTEM_START_TIME1", "SYSTEM_END_TIME1")
)@

ALTER TABLE TFSDB2S.GLIS_HAND_OFF_FILE
ALTER COLUMN TRAN_DES_DOCUMENT_NUMBER SET DATA TYPE VARCHAR(100)@

CALL SYSPROC.ADMIN_CMD('REORG TABLE TFSDB2S.GLIS_HAND_OFF_FILE')@

ALTER TABLE TFSDB2S.GLIS_HAND_OFF_FILE ADD CONSTRAINT "GLIS_HAND_OFF_FILE_PK" PRIMARY KEY ("GLIS_ID")@

CREATE TRIGGER "GLIS_HAND_OFF_FILE_INS_PK"
    BEFORE INSERT ON TFSDB2S.GLIS_HAND_OFF_FILE
    REFERENCING  NEW AS NEW_ROW
    FOR EACH ROW
SET NEW_ROW.GLIS_ID = HEX(GENERATE_UNIQUE())@

CREATE TABLE TFSDB2S.GLIS_HAND_OFF_FILE_HIST(
    GLIS_ID VARCHAR(26) NOT NULL,
    COMPANY_NUMBER VARCHAR(4),
    ACCOUNT_NUMBER VARCHAR(50),
    UCPB_ACCOUNTING_CODE VARCHAR(100),
    UCPB_PARTICULARS VARCHAR(100),
    TRANSACTION_CODE CHAR(2),
    RESP_CTR_NUMBER VARCHAR(10),
    SOURCE_CODE VARCHAR(3),
    AMOUNT DECIMAL(15,2),
    PESOAMOUNT DECIMAL(15,2),
    DATE TIMESTAMP,
    REF_TRAN_SEQ_NUMBER VARCHAR(8),
    TRAN_DES_DOCUMENT_NUMBER VARCHAR(25),
    IS_POSTED CHAR(1) DEFAULT 'N' NOT NULL,
    IS_APPROVED CHAR(1) DEFAULT 'N' NOT NULL,
    CREATED_BY VARCHAR(20),
    MODIFIED_BY VARCHAR(20),
    APPROVED_BY VARCHAR(20),
    CREATED_DATE TIMESTAMP,
    MODIFIED_DATE TIMESTAMP,
    APPROVED_DATE TIMESTAMP,
    REMARKS VARCHAR(500),
    JLRFID SMALLINT,
    ACCENTRY_ID BIGINT,
    SYSTEM_START_TIME1 TIMESTAMP(12) NOT NULL, 
    SYSTEM_END_TIME1 TIMESTAMP(12) NOT NULL, 
    TRANS_ID1 TIMESTAMP(12)
)@

CALL SYSPROC.ADMIN_CMD('REORG TABLE TFSDB2S.GLIS_HAND_OFF_FILE_HIST')@

COMMENT ON COLUMN "TFSDB2S"."GLIS_HAND_OFF_FILE"."ACCOUNT_NUMBER" IS
'LBP Account Number'@

COMMENT ON COLUMN "TFSDB2S"."GLIS_HAND_OFF_FILE"."AMOUNT" IS
'Amount'@

COMMENT ON COLUMN "TFSDB2S"."GLIS_HAND_OFF_FILE"."COMPANY_NUMBER" IS
'Company Number'@

COMMENT ON COLUMN "TFSDB2S"."GLIS_HAND_OFF_FILE"."DATE" IS
'Date'@

COMMENT ON COLUMN "TFSDB2S"."GLIS_HAND_OFF_FILE"."REF_TRAN_SEQ_NUMBER" IS
'Reference ID/Transaction Seq. Number'@

COMMENT ON COLUMN "TFSDB2S"."GLIS_HAND_OFF_FILE"."RESP_CTR_NUMBER" IS
'Responsibility Center Number'@

COMMENT ON COLUMN "TFSDB2S"."GLIS_HAND_OFF_FILE"."SOURCE_CODE" IS
'Source Code'@

COMMENT ON COLUMN "TFSDB2S"."GLIS_HAND_OFF_FILE"."TRANSACTION_CODE" IS
'Transaction Code'@

COMMENT ON COLUMN "TFSDB2S"."GLIS_HAND_OFF_FILE"."TRAN_DES_DOCUMENT_NUMBER" IS
'Transaction Description/Document Number'@

CALL SYSPROC.ADMIN_CMD('REORG TABLE TFSDB2S.GLIS_HAND_OFF_FILE')@

CREATE TABLE TFSDB2S.COMPANY_NUMBERS(
    CODE VARCHAR(4),
    DESCRIPTION VARCHAR(100),
    BOOKCODE VARCHAR(20),
    BOOKCURRENCY VARCHAR(20)
)@

INSERT INTO TFSDB2S.COMPANY_NUMBERS(CODE, DESCRIPTION, BOOKCODE, BOOKCURRENCY) VALUES
('1001','PHP','RG','PHP'),
('1002','Regular USD','RG','USD'),
('1003','Regular JPY','RG','JPY'),
('1004','Regular GBP','RG','GBP'),
('1005','Regular EUR','RG','EUR'),
('1006','Regular SGD','RG','SGD'),
('1007','Regular CHF','RG','CHF'),
('1008','Regular TWD','RG','TWD'),
('1009','Regular AUD','RG','AUD'),
('1010','Regular HKD','RG','HKD'),
('1011','Regular CAD','RG','CAD'),
('1012','Regular SAR','RG','SAR'),
('1013','Regular IDR','RG','IDR'),
('1014','Regular BHD','RG','BHD'),
('1015','Regular THB','RG','THB'),
('1016','Regular AED','RG','AED'),
('1017','Regular BND','RG','BND'),
('2002','FCDU USD','FC','USD'),
('2003','FCDU JPY','FC','JPY'),
('2004','FCDU GBP','FC','GBP'),
('2005','FCDU EUR','FC','EUR'),
('2006','FCDU SGD','FC','SGD'),
('2007','FCDU CHF','FC','CHF'),
('2008','FCDU TWD','FC','TWD'),
('2009','FCDU AUD','FC','AUD'),
('2010','FCDU HKD','FC','HKD'),
('2011','FCDU CAD','FC','CAD'),
('2012','FCDU SAR','FC','SAR'),
('2013','FCDU IDR','FC','IDR'),
('2014','FCDU BHD','FC','BHD'),
('2015','FCDU THB','FC','THB'),
('2016','FCDU AED','FC','AED'),
('2017','FCDU BND','FC','BND')@

--SELECT COMPANY_NUMBER, ACCOUNT_CODE, TRANSACTION_CODE, RESP_CTR_NUMBER, SOURCE_CODE
--    , AMOUNT, DATE, REF_TRAN_SEQ_NUMBER, TRAN_DES_DOCUMENT_NUMBER
--FROM TFSDB2S.GLIS_HAND_OFF_FILE
--WHERE IS_POSTED = 'N'@
--
--SELECT * FROM TFSDB2S.GLIS_HAND_OFF_FILE@
--
--DELETE FROM TFSDB2S.GLIS_HAND_OFF_FILE@
--
--UPDATE TFSDB2S.GLIS_HAND_OFF_FILE
--SET IS_POSTED = 'N', IS_APPROVED = 'Y', DATE = '2023-01-26'@
