CREATE TABLE TFSDB2S.JHPARL(
JLRFID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 100 INCREMENT BY 1 MINVALUE -32768 MAXVALUE 32767 NO CYCLE CACHE 20 NO ORDER ),
JLUNIT DECIMAL(5, 0) NOT NULL,JLTYPE VARCHAR(2) NOT NULL,JLRFBR DECIMAL(3, 0) NOT NULL,JLNLVL VARCHAR(5) NOT NULL, LBP_RESP_CTR_NUMBER VARCHAR(10),
JLDESC VARCHAR(40) NOT NULL,
JLUSRN VARCHAR(10), 
JLDAT6 DECIMAL(6 , 0),
CREATED_BY VARCHAR(20) NOT NULL, 
MODIFIED_BY VARCHAR(20), 
APPROVED_BY VARCHAR(20), 
CREATED_DATE TIMESTAMP NOT NULL, 
MODIFIED_DATE TIMESTAMP, 
APPROVED_DATE TIMESTAMP,
AREA_CODE VARCHAR(5), 
REGION_CODE VARCHAR(5), 
UNIT_NAME VARCHAR(100) NOT NULL, 
IS_BOC_PROCESSOR CHAR(1) DEFAULT 'N' NOT NULL,
LBP_UNIT_CODE VARCHAR(3),
NEW_UNIT_CODE VARCHAR(3));
ALTER TABLE "TFSDB2S"."JHPARL" ADD CONSTRAINT "JHPARL_PK" PRIMARY KEY
    ("JLRFID");

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."APPROVED_BY" IS
'Approved By';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."APPROVED_DATE" IS
'Approved Date';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."AREA_CODE" IS
'Area Code';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."UNIT_NAME" IS
'Unit Name';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."CREATED_BY" IS
'Created By';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."CREATED_DATE" IS
'Created Date';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."IS_BOC_PROCESSOR" IS
'Is BOC Processor';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."JLDAT6" IS
'LAST MAINTAINED DATE';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."JLDESC" IS
'DESCRIPTION';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."JLNLVL" IS
'NEXT LEVEL';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."JLRFBR" IS
'BRANCH_UNIT_CODE';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."JLTYPE" IS
'UNIT TYPE';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."JLUNIT" IS
'UNIT CODE';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."JLUSRN" IS
'LAST MAINTAINED BY';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."LBP_UNIT_CODE" IS
'LBP Business Unit Code';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."LBP_RESP_CTR_NUMBER" IS
'LBP Responsibility Center Number';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."MODIFIED_BY" IS
'Modified By';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."MODIFIED_DATE" IS
'Modified Date';

COMMENT ON COLUMN "TFSDB2S"."JHPARL"."REGION_CODE" IS
'Region Code';

CALL SYSPROC.ADMIN_CMD('REORG TABLE TFSDB2S.JHPARL');