--<ScriptOptions statementTerminator="@"/>
CREATE OR REPLACE TRIGGER TRG_UPDATE_UNIT_BOC
AFTER UPDATE ON TFSDB2S.JHPARL
REFERENCING NEW AS NEWUNIT OLD AS OLDUNIT
FOR EACH ROW
BEGIN ATOMIC
    DECLARE V_UNIT_TEMPLATE VARCHAR(10);
    DECLARE V_ID BIGINT;

    IF NEWUNIT.IS_BOC_PROCESSOR <> OLDUNIT.IS_BOC_PROCESSOR AND NEWUNIT.IS_BOC_PROCESSOR = 'Y' THEN
        IF NEWUNIT.JLRFBR <> '111' THEN
            SET V_UNIT_TEMPLATE = '111';
            INSERT INTO TFSDB2S.GLMAST(BRANCH, ACCTNO, GMCTYP, BOOKCD, TITLE, SHORTT, ACTYPE, VALPST)
            SELECT NEWUNIT.JLRFBR, ACCTNO, GMCTYP, BOOKCD, TITLE, SHORTT, ACTYPE, VALPST
            FROM TFSDB2S.GLMAST A
            WHERE BRANCH = V_UNIT_TEMPLATE
                AND NOT EXISTS(SELECT 1 FROM TFSDB2S.GLMAST
                    WHERE BRANCH = NEWUNIT.JLRFBR AND ACCTNO = A.ACCTNO AND GMCTYP = A.GMCTYP AND BOOKCD = A.BOOKCD);
    
            IF NOT EXISTS(SELECT 1 FROM DOC_NUM_SEQUENCE WHERE UNIT_CODE = NEWUNIT.JLRFBR AND SEQUENCE_YEAR = TO_CHAR(NOW, 'YYYY')) THEN
                SET V_ID = (SELECT MAX(ID) FROM DOC_NUM_SEQUENCE);
                FOR REC AS (SELECT DOCUMENT_TYPE FROM DOC_NUM_SEQUENCE
                        WHERE UNIT_CODE = V_UNIT_TEMPLATE
                        AND SEQUENCE_YEAR = TO_CHAR(NOW, 'YYYY')) DO
                    SET V_ID = V_ID + 1;
                    INSERT INTO DOC_NUM_SEQUENCE(ID, DOCUMENT_TYPE, SEQUENCE, UNIT_CODE, SEQUENCE_YEAR)
                    VALUES(V_ID, REC.DOCUMENT_TYPE, 1, NEWUNIT.JLRFBR, TO_CHAR(NOW, 'YYYY'));
                END FOR;
            END IF;
        END IF;
    END IF;
END
