--<ScriptOptions statementTerminator="@"/>
CREATE OR REPLACE TRIGGER TRG_NEW_UNIT
AFTER INSERT ON TFSDB2S.JHPARL
REFERENCING NEW AS NEWUNIT
FOR EACH ROW
BEGIN ATOMIC
    DECLARE V_UNIT_TEMPLATE VARCHAR(10);
    DECLARE V_ID BIGINT;

    IF UCASE(NEWUNIT.IS_BOC_PROCESSOR) = 'Y' THEN
        SET V_UNIT_TEMPLATE = '111';
    END IF;

    IF V_UNIT_TEMPLATE IS NOT NULL AND NEWUNIT.JLRFBR <> '111' THEN
        INSERT INTO TFSDB2S.GLMAST(BRANCH, ACCTNO, GMCTYP, BOOKCD, TITLE, SHORTT, ACTYPE, VALPST)
        SELECT NEWUNIT.JLRFBR, ACCTNO, GMCTYP, BOOKCD, TITLE, SHORTT, ACTYPE, VALPST
        FROM TFSDB2S.GLMAST A
        WHERE BRANCH = V_UNIT_TEMPLATE
            AND NOT EXISTS(SELECT 1 FROM TFSDB2S.GLMAST
                WHERE BRANCH = NEWUNIT.JLRFBR AND ACCTNO = A.ACCTNO AND GMCTYP = A.GMCTYP AND BOOKCD = A.BOOKCD);

        IF NOT EXISTS(SELECT 1 FROM DOC_NUM_SEQUENCE WHERE UNIT_CODE = NEWUNIT.JLRFBR AND SEQUENCE_YEAR = TO_CHAR(NOW, 'YYYY')) THEN
            SET V_ID = (SELECT MAX(ID) FROM DOC_NUM_SEQUENCE);
            FOR REC AS (SELECT DOCUMENT_TYPE FROM DOC_NUM_SEQUENCE
                    WHERE UNIT_CODE = V_UNIT_TEMPLATE
                    AND SEQUENCE_YEAR = TO_CHAR(NOW, 'YYYY')) DO
                SET V_ID = V_ID + 1;
                INSERT INTO DOC_NUM_SEQUENCE(ID, DOCUMENT_TYPE, SEQUENCE, UNIT_CODE, SEQUENCE_YEAR)
                VALUES(V_ID, REC.DOCUMENT_TYPE, 1, NEWUNIT.JLRFBR, TO_CHAR(NOW, 'YYYY'));
            END FOR;
        END IF;
    END IF;

	IF NEWUNIT.JLTYPE = 'BR' THEN
	    -- CREATE REGULAR HOLIDAYS FOR THE UNIT
	    FOR REC AS (
	        SELECT * FROM (
	            SELECT DISTINCT CDATE, DESCRIPTION
	            , DATE(TIMESTAMP_FORMAT(LPAD(TO_CHAR(CDATE), 6, '0'),'MMDDYY')) HOLIDAY_DATE
	            FROM TFSDB2S.JHCLDR WHERE IS_REGULAR = 'Y' AND HOLDAY = 'Y')
	        WHERE TO_CHAR(HOLIDAY_DATE, 'YYYY') = TO_CHAR(NOW(), 'YYYY')
	    ) DO
	        INSERT INTO TFSDB2S.JHCLDR(CDATE, HOLDAY, CBRNBR, CREATED_BY
	            , DESCRIPTION, IS_REGULAR, JLRFID)
	        SELECT TO_CHAR(ADD_YEARS(REC.HOLIDAY_DATE, A.NUM), 'MMDDYY'), 'Y', NEWUNIT.JLRFBR, 'UNITTRIGGER', REC.DESCRIPTION, 'Y', NEWUNIT.JLRFID
	        FROM TABLE(VALUES(0), (1), (2), (3)) A(NUM);
	    END FOR;
    END IF;
END@
