package com.ucpb.tfs.domain.product.infrastructure.repositories.hibernate;

import com.ucpb.tfs.domain.product.*;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.context.transaction.TransactionConfiguration;
import org.springframework.transaction.annotation.Transactional;

import java.util.Currency;

import static junit.framework.Assert.assertEquals;
import static junit.framework.Assert.assertNotNull;

/**
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration("classpath:*transactionlog-app-context.xml")
@TransactionConfiguration
@Transactional
public class HibernateNonLcRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private HibernateNonLcRepository hibernateNonLcRepository;


    @Before
    public void setup(){
        jdbcTemplate.execute("DELETE FROM DOCUMENTAGAINSTACCEPTANCE");
        jdbcTemplate.execute("DELETE FROM TRADEPRODUCT");

    }

    @Test
    public void successfullyRetrieveAllDaDetails(){

        jdbcTemplate.execute("INSERT INTO TRADEPRODUCT (DOCUMENTNUMBER,PRODUCTTYPE,CIFNUMBER,CIFNAME,MAINCIFNUMBER,MAINCIFNAME,ACCOUNTOFFICER,CCBDBRANCHUNITCODE,FACILITYID,FACILITYTYPE,FACILITYREFERENCENUMBER,ALLOCATIONUNITCODE,STATUS,LONGNAME,ADDRESS1,ADDRESS2,PASSONRATETHIRDTOUSD,PASSONRATETHIRDTOPHP,PASSONRATEUSDTOPHP,SPECIALRATETHIRDTOUSD,SPECIALRATETHIRDTOPHP,SPECIALRATEUSDTOPHP,URR,AMOUNT,CURRENCY) VALUES ('909-06-125-13-00004-6','DA','P005679','PACIFIC ASIA OVE O','P005679','PACIFIC ASIA OVE O','MARIA THERESA DY','125','','',null,null,'ACKNOWLEDGED','ON  PACIFIC ASIA OVERSEAS SHIPPING CORPORATI','G F PASCOR BLDG PASCOR','DRIVE SANTO NINO',null,null,null,null,null,null,44.92000000,214151.00,'USD')");

        jdbcTemplate.execute("INSERT INTO DOCUMENTAGAINSTACCEPTANCE (DOCUMENTNUMBER,TSNUMBER,DOCUMENTTYPE,REMITTINGBANK,REIMBURSINGBANK,PROCESSDATE,REMITTINGBANKREFERENCENUMBER,CURRENCY,AMOUNT,OUTSTANDINGAMOUNT,DATEOFBLAIRWAYBILL,MATURITYDATE,IMPORTERCIFNUMBER,ORIGINALPORT,IMPORTERCBCODE,IMPORTERNAME,IMPORTERADDRESS,SENDERTORECEIVERINFORMATION,BENEFICIARYNAME,BENEFICIARYADDRESS,LASTTRANSACTION,CANCELLEDDATE,SETTLEDDATE,PROCESSINGUNITCODE) VALUES ('909-06-125-13-00004-6',null,'FOREIGN','AAAARSBGXXX',null,{ts '2013-03-15 16:32:38'},'remittingbank','USD',214151.00,214151.00,{ts '2013-03-12 00:00:00'},{ts '2013-03-29 00:00:00'},'P005679','PG - PAPUA NEW GUINEA     - 201','','ON  PACIFIC ASIA OVERSEAS SHIPPING CORPORATI','G F PASCOR BLDG PASCOR\n" +
                "DRIVE SANTO NINO\n" +
                "PARANAQUE CITY','a','benef','add','FX DA Negotiation Acknowledgement',null,null,'909')");

        assertEquals(1,jdbcTemplate.queryForInt("SELECT COUNT(*) FROM DOCUMENTAGAINSTACCEPTANCE,TRADEPRODUCT"));

        DocumentAgainstAcceptance da = hibernateNonLcRepository.getDocumentAgainstAcceptance(new DocumentNumber("909-06-125-13-00004-6"));

        assertEquals(Currency.getInstance("USD"),da.getCurrency());
        assertEquals("PG - PAPUA NEW GUINEA     - 201",da.getOriginalPort());
        assertEquals("P005679",da.getImporterCifNumber());
        assertEquals("PACIFIC ASIA OVE O",da.getMainCifName());
    }

    @Test
    public void successfullyRetrieveAllDpDetails(){
        jdbcTemplate.execute("INSERT INTO TRADEPRODUCT (DOCUMENTNUMBER,PRODUCTTYPE,CIFNUMBER,CIFNAME,MAINCIFNUMBER,MAINCIFNAME,ACCOUNTOFFICER,CCBDBRANCHUNITCODE,FACILITYID,FACILITYTYPE,FACILITYREFERENCENUMBER,ALLOCATIONUNITCODE,STATUS,LONGNAME,ADDRESS1,ADDRESS2,PASSONRATETHIRDTOUSD,PASSONRATETHIRDTOPHP,PASSONRATEUSDTOPHP,SPECIALRATETHIRDTOUSD,SPECIALRATETHIRDTOPHP,SPECIALRATEUSDTOPHP,URR,AMOUNT,CURRENCY) VALUES ('909-09-929-13-00005-5','DP','S040448','STEELASIA MANUFACTUR','S040448','STEELASIA MANUFACTUR','MA. CARMELA LAARNI FELICIDARIO','929','','',null,null,'NEGOTIATED','  STEELASIA MANUFACTURING CORP','2ND FLOOR B2 BONIFACIO','HIGH STREET FORT',null,null,null,null,null,null,44.92000000,131341.00,'USD')");

        jdbcTemplate.execute("INSERT INTO DOCUMENTAGAINSTPAYMENT (DOCUMENTNUMBER,TSNUMBER,DOCUMENTTYPE,REMITTINGBANK,REIMBURSINGBANK,PROCESSDATE,REMITTINGBANKREFERENCENUMBER,CURRENCY,AMOUNT,OUTSTANDINGAMOUNT,DATEOFBLAIRWAYBILL,MATURITYDATE,IMPORTERCIFNUMBER,ORIGINALPORT,IMPORTERCBCODE,IMPORTERNAME,IMPORTERADDRESS,SENDERTORECEIVERINFORMATION,BENEFICIARYNAME,BENEFICIARYADDRESS,LASTTRANSACTION,CANCELLEDDATE,SETTLEDDATE,PROCESSINGUNITCODE) VALUES ('909-09-929-13-00005-5',null,'DOMESTIC',null,null,{ts '2013-03-21 11:01:31'},null,'USD',131341.00,131341.00,{ts '2013-03-12 00:00:00'},null,'S040448',null,null,'STEELASIA MANUFACTUR','2ND FLOOR B2 BONIFACIO\n" +
                "HIGH STREET FORT\n" +
                "BONIFACIO GLOBAL CITY',null,'SELLER NAME','SELLER ADDRESS','DM DP Negotiation',null,null,'909')");

        DocumentAgainstPayment dp = hibernateNonLcRepository.getDocumentAgainstPayment(new DocumentNumber("909-09-929-13-00005-5"));
        assertEquals(Currency.getInstance("USD"),dp.getCurrency());
        assertEquals("STEELASIA MANUFACTUR",dp.getMainCifName());
        assertEquals("909",dp.getProcessingUnitCode());
    }

    @Test
    public void successfullyRetrieveAllDRDetails(){
        jdbcTemplate.execute("INSERT INTO TRADEPRODUCT (DOCUMENTNUMBER,PRODUCTTYPE,CIFNUMBER,CIFNAME,MAINCIFNUMBER,MAINCIFNAME,ACCOUNTOFFICER,CCBDBRANCHUNITCODE,FACILITYID,FACILITYTYPE,FACILITYREFERENCENUMBER,ALLOCATIONUNITCODE,STATUS,LONGNAME,ADDRESS1,ADDRESS2,PASSONRATETHIRDTOUSD,PASSONRATETHIRDTOPHP,PASSONRATEUSDTOPHP,SPECIALRATETHIRDTOUSD,SPECIALRATETHIRDTOPHP,SPECIALRATEUSDTOPHP,URR,AMOUNT,CURRENCY) VALUES ('909-08-929-13-00003-2','DR','L000395','LEPANTO CONSOLID','L000395','LEPANTO CONSOLID','REGINA TERESA RODRIGUEZ','929','','',null,null,'CANCELLED','LEPANTO CONSOLID','21ST FLOOR LEPANTO BLDG','8747 PASEO DE ROXAS',null,null,null,null,null,null,44.92000000,13141.00,'USD')");

        jdbcTemplate.execute("INSERT INTO DIRECTREMITTANCE (DOCUMENTNUMBER,TSNUMBER,DOCUMENTTYPE,REMITTINGBANK,REIMBURSINGBANK,PROCESSDATE,REMITTINGBANKREFERENCENUMBER,CURRENCY,AMOUNT,OUTSTANDINGAMOUNT,DATEOFBLAIRWAYBILL,MATURITYDATE,IMPORTERCIFNUMBER,ORIGINALPORT,IMPORTERCBCODE,IMPORTERNAME,IMPORTERADDRESS,SENDERTORECEIVERINFORMATION,BENEFICIARYNAME,BENEFICIARYADDRESS,LASTTRANSACTION,CANCELLEDDATE,SETTLEDDATE,PROCESSINGUNITCODE) VALUES ('909-08-929-13-00003-2',null,'FOREIGN','AAAARSBGXXX',null,{ts '2013-03-06 21:20:54'},'','USD',13141.00,13141.00,{ts '2013-03-05 00:00:00'},{ts '2013-03-27 00:00:00'},'','BI - BURUNDI              - 125','233120015','OMAR GENERAL TRADING','GATE NO. 2 ROJO COMPOUND\n" +
                "STA. CATALINA ZAMBOANGA\n" +
                "\n" +
                "','sender to receiver information','beneficiary name','beneficiary address','FX DR Cancellation',{ts '2013-04-02 11:48:29'},null,'909')");


        DirectRemittance dr = hibernateNonLcRepository.getDirectRemittance(new DocumentNumber("909-08-929-13-00003-2"));
        assertEquals(Currency.getInstance("USD"),dr.getCurrency());
        assertEquals("LEPANTO CONSOLID",dr.getMainCifName());
        assertNotNull(dr.getCurrency());
    }

    @Test
    public void successfullyRetrieveAllOaDetails(){

        jdbcTemplate.execute("INSERT INTO TRADEPRODUCT (DOCUMENTNUMBER,PRODUCTTYPE,CIFNUMBER,CIFNAME,MAINCIFNUMBER,MAINCIFNAME,ACCOUNTOFFICER,CCBDBRANCHUNITCODE,FACILITYID,FACILITYTYPE,FACILITYREFERENCENUMBER,ALLOCATIONUNITCODE,STATUS,LONGNAME,ADDRESS1,ADDRESS2,PASSONRATETHIRDTOUSD,PASSONRATETHIRDTOPHP,PASSONRATEUSDTOPHP,SPECIALRATETHIRDTOUSD,SPECIALRATETHIRDTOPHP,SPECIALRATEUSDTOPHP,URR,AMOUNT,CURRENCY) VALUES ('909-07-929-13-00003-4','OA','A047688','ASIAN COATINGS PHIL','A047688','ASIAN COATINGS PHIL','ALEXANDER BORJA','929','','',null,null,'NEGOTIATED','  ASIAN COATINGS PHIL  INC/WEL-BEST/IRVIN','NO 48 AMANG  RODRIGUEZ','SANTOLAN',null,null,null,null,null,null,44.92000000,536332.00,'JPY')");

        jdbcTemplate.execute("INSERT INTO OPENACCOUNT (DOCUMENTNUMBER,TSNUMBER,DOCUMENTTYPE,REMITTINGBANK,REIMBURSINGBANK,PROCESSDATE,REMITTINGBANKREFERENCENUMBER,CURRENCY,AMOUNT,OUTSTANDINGAMOUNT,DATEOFBLAIRWAYBILL,MATURITYDATE,IMPORTERCIFNUMBER,ORIGINALPORT,IMPORTERCBCODE,IMPORTERNAME,IMPORTERADDRESS,SENDERTORECEIVERINFORMATION,BENEFICIARYNAME,BENEFICIARYADDRESS,LASTTRANSACTION,CANCELLEDDATE,SETTLEDDATE,PROCESSINGUNITCODE) VALUES ('909-07-929-13-00003-4',null,'FOREIGN','AAAARSBGXXX',null,{ts '2013-04-02 15:22:04'},'','JPY',536332.00,536332.00,{ts '2013-04-01 00:00:00'},{ts '2013-04-23 00:00:00'},'A047688','BO - BOLIVIA              - 115','','  ASIAN COATINGS PHIL  INC/WEL-BEST/IRVIN','NO 48 AMANG  RODRIGUEZ\n" +
                "SANTOLAN\n" +
                "PASIG CITY','SENDER TO RECEIVER INFORMATION','beneficiary name','beneficiary address','FX OA Negotiation',null,null,'909')");

        OpenAccount oa = hibernateNonLcRepository.getOpenAccount(new DocumentNumber("909-07-929-13-00003-4"));
        assertEquals(Currency.getInstance("JPY"),oa.getCurrency());

    }


}
