CREATE TABLE "ACCOUNTLOG"
(
    ID bigint PRIMARY KEY NOT NULL,
    DATE_CREATED timestamp,
	ACCOUNTNUMBER VARCHAR(50),
	ACCOUNTTYPE VARCHAR(15),
	INITIALDEPOSIT DECIMAL(18,2),
	ACCOUNTPURPOSE VARCHAR(50),
	MONTHLYESTIMATEDTRANSACTIONCOUNT INT,
	MONTHLYESTIMATEDTRANSACTIONVOLUME INT,
	TRANSACTIONTYPES VARCHAR(15),
	BRANCHCODE VARCHAR(15),
	OPENINGDATE TIMESTAMP,
	CLOSINGDATE TIMESTAMP,
	RISKSCORE VARCHAR(1),
	ACCOUNTBALANCE DECIMAL(18,2),
	APPLICATIONCODE VARCHAR(2),
	STATUS VARCHAR(5),
	ACCOUNTCURRENCY VARCHAR(3),
	PAYROLLTAG VARCHAR(1)
)
;
CREATE UNIQUE INDEX SQL121201145524860 ON "ACCOUNTLOG"(ID)
;
