CREATE SEQUENCE TRADE_SERVICE_REF_NUM_SEQUENCE START WITH 1 INCREMENT BY 1 NO MAXVALUE MINVALUE 00001 CYCLE;
CREATE SEQUENCE MT_MESSAGE_SEQUENCE START WITH 1 INCREMENT BY 1 NO MAXVALUE MINVALUE 00001 CYCLE
