--<ScriptOptions statementTerminator="@">
CREATE OR REPLACE PROCEDURE TFSDB2S.GET_LOAN_STATUS(IN P_SEQUENCENUMBER DECIMAL(5, 0))
SPECIFIC GET_LOAN_STATUS
DYNAMIC RESULT SETS 1
LANGUAGE SQL
P1: BEGIN
    DECLARE V_PNNUMBER DECIMAL(19, 0);
    DECLARE V_CURTYP CHAR(4);
    DECLARE C_LOAN_DETAILS CURSOR WITH RETURN FOR
        SELECT * FROM TFSDB2S.LNTFINT WHERE TRSEQ = P_SEQUENCENUMBER;

    SET (V_PNNUMBER, V_CURTYP) = (SELECT ACCTNO, CURTYP FROM TFSDB2S.LNTFINT WHERE TRSEQ = P_SEQUENCENUMBER);

    OPEN C_LOAN_DETAILS;
    
    UPDATE TFSDB2S.LNTFINT
    SET PRODUCT_ID = (SELECT A.PROD_ID FROM TFSDB2S.PROD_PAYMNT_CICLS_MAPPING A, PAYMENTDETAIL B
        WHERE A.MOP_PRODUCT = B.PAYMENTINSTRUMENTTYPE
            AND B.PNNUMBER = V_PNNUMBER)
    WHERE TRSEQ = P_SEQUENCENUMBER;
END P1@