
--<ScriptOptions statementTerminator="@">

CREATE OR REPLACE PROCEDURE TFSDB2S.INQUIRE_CONTIGENT(
    IN P_CIFNUMBER VARCHAR(7),
    IN P_DOCUMENTNUMBER VARCHAR(21),
    IN P_ORIGINALAMOUNT DECIMAL(19, 2),
    IN P_OUTSTANDINGBALANCE DECIMAL(19, 2),
    IN P_TRANSACTIONDATE DECIMAL(6 , 0),
    IN P_TRANSACTIONTIME DECIMAL(6 , 0),
    IN P_PHPAMOUNT DECIMAL(19, 2),
    IN P_PHPOUTSTANDINGBALANCE DECIMAL(19, 2),
    IN P_CURRENCYCODE VARCHAR(4),
    IN P_ALFLG CHAR(1),
    IN P_STATUSDESCRIPTION VARCHAR(20),
    IN P_FACILITYREFERENCENUMBER VARCHAR(20)
)
SPECIFIC INQUIRE_CONTIGENT
LANGUAGE SQL
P1: BEGIN
    DECLARE V_PRODUCT_ID INTEGER;
    DECLARE V_IRR_RATE DECIMAL(13, 7);
    DECLARE V_DOCUMENT_CLASS VARCHAR(20);
    DECLARE V_TOTAL_TLOSBAL DECIMAL(19, 2);
    DECLARE V_INTERMEDIATE_BALANCE DECIMAL(31, 8);
    DECLARE V_SPECIAL_RATE_USD DECIMAL(31, 8);
    DECLARE V_SPECIAL_RATE_THIRD DECIMAL(31, 8);


   IF NOT EXISTS ( SELECT 1 FROM TFSDB2S.LNCLST WHERE ACCTNO = REPLACE(P_DOCUMENTNUMBER, '-', '') ) THEN
        SET V_PRODUCT_ID = (
        SELECT PROD_ID
        FROM TFSDB2S.PROD_PAYMNT_CICLS_MAPPING
        WHERE CICLS_PRODUCT_CODE = '250'
        FETCH FIRST ROW ONLY
    );

        SET V_DOCUMENT_CLASS = (
        SELECT C.DOCUMENTCLASS
        FROM (
            SELECT TRADEPRODUCTNUMBER, MAX(CREATEDDATE) AS CREATEDDATE
            FROM TRADESERVICE
            WHERE DOCUMENTCLASS IN ('DA', 'OA', 'LC', 'INDEMNITY', 'OTHERS')
              AND SERVICETYPE NOT IN ('UA_LOAN_SETTLEMENT')
            GROUP BY TRADEPRODUCTNUMBER
        ) B
        INNER JOIN TRADESERVICE C
            ON B.TRADEPRODUCTNUMBER = C.TRADEPRODUCTNUMBER
           AND B.CREATEDDATE = C.CREATEDDATE
        WHERE REPLACE(B.TRADEPRODUCTNUMBER, '-', '') = REPLACE(P_DOCUMENTNUMBER, '-', '')
    );

        SET V_IRR_RATE = (
        SELECT JFXDCR
        FROM TFSDB2S.JHFXDT
        WHERE JFXDBC = 'PHP'
          AND JFXDCD = P_CURRENCYCODE
          AND JFXDRN = 3
    );

             SET V_SPECIAL_RATE_USD = COALESCE((SELECT CAST(SPECIALRATEUSDTOPHPSERVICECHARGE AS DECIMAL(31, 8)) FROM TRADESERVICE WHERE REPLACE(DOCUMENTNUMBER, '-', '') = REPLACE(P_DOCUMENTNUMBER, '-', '') AND SERVICETYPE = 'OPENING'), 1);
    SET V_SPECIAL_RATE_THIRD = COALESCE((SELECT CAST(SPECIALRATETHIRDTOUSDSERVICECHARGE AS DECIMAL(31, 8)) FROM TRADESERVICE WHERE REPLACE(DOCUMENTNUMBER, '-', '') = REPLACE(P_DOCUMENTNUMBER, '-', '') AND SERVICETYPE = 'OPENING'), 1);

        IF UPPER(TRIM(P_CURRENCYCODE)) = 'PHP' THEN
        SET V_INTERMEDIATE_BALANCE = CAST(P_OUTSTANDINGBALANCE AS DECIMAL(31, 8));
    ELSEIF UPPER(TRIM(P_CURRENCYCODE)) = 'USD' THEN
        SET V_INTERMEDIATE_BALANCE = CAST(P_OUTSTANDINGBALANCE AS DECIMAL(31, 8)) * V_SPECIAL_RATE_USD;
    ELSE
        SET V_INTERMEDIATE_BALANCE = CAST(P_OUTSTANDINGBALANCE AS DECIMAL(31, 8)) * V_SPECIAL_RATE_THIRD * V_SPECIAL_RATE_USD;
    END IF;

    SET V_TOTAL_TLOSBAL = CAST(ROUND(V_INTERMEDIATE_BALANCE, 2) AS DECIMAL(19, 2));
    

        INSERT INTO TFSDB2S.LNCLST (
            SYSCOD, CIFNO, ACCTNO, ORGLMT, TOSBAL, PRODUCT,
            DATE, TIME, LORGAM, TLOSBAL, CURTYP, ALFLG, STADSC, AFCPNO, NAME,
            CIFID, CIFCOD, PRODSC, ADBBAL, ORGSBL, LOCSBL, PRODUCT_ID,
            ORGLMT_IRR, TOSBAL_IRR
        )
        VALUES (
            'TF', P_CIFNUMBER, P_DOCUMENTNUMBER, P_ORIGINALAMOUNT, P_OUTSTANDINGBALANCE, '25',
            P_TRANSACTIONDATE, P_TRANSACTIONTIME, P_PHPAMOUNT, V_TOTAL_TLOSBAL, P_CURRENCYCODE,
            P_ALFLG, P_STATUSDESCRIPTION, P_FACILITYREFERENCENUMBER, ' ', ' ', ' ',
            'CONTINGENT ACCOUNTS - ' || V_DOCUMENT_CLASS, 0, 0, 0, V_PRODUCT_ID,
            CASE WHEN P_CURRENCYCODE = 'PHP' THEN P_ORIGINALAMOUNT
                ELSE P_ORIGINALAMOUNT * V_IRR_RATE
            END,
            CASE WHEN P_CURRENCYCODE = 'PHP' THEN P_OUTSTANDINGBALANCE
                ELSE P_OUTSTANDINGBALANCE * V_IRR_RATE
            END
        );
    END IF;
END P1 