--<ScriptOptions statementTerminator="@">
CREATE OR REPLACE PROCEDURE TFSDB2S.INQUIRE_CONTIGENT(IN P_CIFNUMBER VARCHAR(7)
    , IN P_DOCUMENTNUMBER VARCHAR(21), IN P_ORIGINALAMOUNT DECIMAL(19, 2)
    , IN P_OUTSTANDINGBALANCE DECIMAL(19, 2), IN P_TRANSACTIONDATE DECIMAL(6 , 0)
    , IN P_TRANSACTIONTIME DECIMAL(6 , 0), IN P_PHPAMOUNT DECIMAL(19, 2)
    , IN P_PHPOUTSTANDINGBALANCE DECIMAL(19, 2), IN P_CURRENCYCODE VARCHAR(4)
    , IN P_ALFLG CHAR(1)
    , IN P_STATUSDESCRIPTION VARCHAR(20), IN P_FACILITYREFERENCENUMBER VARCHAR(20))
SPECIFIC INQUIRE_CONTIGENT
LANGUAGE SQL
--######################################################################################################
--# Description:    Saves facility availments.
--# Created by:     Cedrick C. Nungay 
--# Date created:   02/19/2024
--######################################################################################################
P1: BEGIN
    DECLARE V_PRODUCT_ID INTEGER;
    DECLARE V_IRR_RATE DECIMAL(13, 7);
    DECLARE V_DOCUMENT_CLASS VARCHAR(20);

    SET (V_PRODUCT_ID,V_DOCUMENT_CLASS) = (
       SELECT D.PROD_ID,C.DOCUMENTCLASS
       FROM (SELECT TRADEPRODUCTNUMBER, MAX(CREATEDDATE) CREATEDDATE
               FROM TRADESERVICE
               WHERE DOCUMENTCLASS IN ('DA','OA','LC','INDEMNITY', 'OTHERS') AND SERVICETYPE NOT IN ('UA_LOAN_SETTLEMENT')
               GROUP BY TRADEPRODUCTNUMBER) B
       INNER JOIN TRADESERVICE C
       ON B.TRADEPRODUCTNUMBER = C.TRADEPRODUCTNUMBER
           AND B.CREATEDDATE = C.CREATEDDATE
       LEFT JOIN TFSDB2S.PROD_PAYMNT_CICLS_MAPPING D
       ON C.DOCUMENTCLASS = D.MOP_PRODUCT
                 WHERE REPLACE(B.TRADEPRODUCTNUMBER, '-', '') = REPLACE(P_DOCUMENTNUMBER, '-', '') );

    SET V_IRR_RATE = (SELECT JFXDCR FROM TFSDB2S.JHFXDT
        WHERE JFXDBC = 'PHP' AND JFXDCD = P_CURRENCYCODE AND JFXDRN = 3);

    INSERT INTO TFSDB2S.LNCLST(SYSCOD, CIFNO, ACCTNO, ORGLMT, TOSBAL, PRODUCT
        , DATE, TIME, LORGAM, TLOSBAL, CURTYP, ALFLG, STADSC, AFCPNO, NAME
        , CIFID, CIFCOD, PRODSC, ADBBAL, ORGSBL, LOCSBL, PRODUCT_ID
        , ORGLMT_IRR, TOSBAL_IRR)
    VALUES('TF', P_CIFNUMBER, P_DOCUMENTNUMBER, P_ORIGINALAMOUNT
        , P_OUTSTANDINGBALANCE, '25', P_TRANSACTIONDATE, P_TRANSACTIONTIME
        , P_PHPAMOUNT, P_PHPOUTSTANDINGBALANCE, P_CURRENCYCODE, P_ALFLG
        , P_STATUSDESCRIPTION, P_FACILITYREFERENCENUMBER, ' ', ' ', ' '
        , 'CONTINGENT ACCOUNTS' ||' - ' || V_DOCUMENT_CLASS, 0, 0, 0, V_PRODUCT_ID
        , (P_ORIGINALAMOUNT * V_IRR_RATE), (P_OUTSTANDINGBALANCE * V_IRR_RATE));
END P1@