

--<ScriptOptions statementTerminator="@">
CREATE OR REPLACE PROCEDURE TFSDB2S.UPDATE_CONTINGENT(IN P_CIFNUMBER VARCHAR(7)
                                                    , IN P_ORIGINALAMOUNT DECIMAL(19, 2)
                                                    , IN P_OUTSTANDINGBALANCE DECIMAL(19, 2)
                                                    , IN P_TRANSACTIONDATE DECIMAL(6 , 0)
                                                    , IN P_TRANSACTIONTIME DECIMAL(6 , 0)
                                                    , IN P_PHPAMOUNT DECIMAL(19, 2)
                                                    , IN P_PHPOUTSTANDINGBALANCE DECIMAL(19, 2)
                                                    , IN P_CURRENCYCODE VARCHAR(4)
                                                    , IN P_STATUSDESCRIPTION VARCHAR(20)
                                                    , IN P_FACILITYREFERENCENUMBER VARCHAR(20)
													, IN P_DOCUMENTNUMBER VARCHAR(21))
SPECIFIC UPDATE_CONTINGENT
LANGUAGE SQL
P1: BEGIN
    DECLARE V_TOTAL_TLOSBAL DECIMAL(19, 2);
    DECLARE V_INTERMEDIATE_BALANCE DECIMAL(31, 8);
    DECLARE V_SPECIAL_RATE_USD DECIMAL(31, 8);
    DECLARE V_SPECIAL_RATE_THIRD DECIMAL(31, 8);

	IF EXISTS ( SELECT 1 FROM TFSDB2S.LNCLST WHERE ACCTNO = REPLACE(P_DOCUMENTNUMBER, '-', '') ) THEN

	SET V_SPECIAL_RATE_USD = COALESCE((SELECT CAST(SPECIALRATEUSDTOPHPSERVICECHARGE AS DECIMAL(31, 8)) FROM TRADESERVICE WHERE REPLACE(DOCUMENTNUMBER, '-', '') = REPLACE(P_DOCUMENTNUMBER, '-', '') AND SERVICETYPE = 'OPENING'), 1);
    SET V_SPECIAL_RATE_THIRD = COALESCE((SELECT CAST(SPECIALRATETHIRDTOUSDSERVICECHARGE AS DECIMAL(31, 8)) FROM TRADESERVICE WHERE REPLACE(DOCUMENTNUMBER, '-', '') = REPLACE(P_DOCUMENTNUMBER, '-', '') AND SERVICETYPE = 'OPENING'), 1);

        IF UPPER(TRIM(P_CURRENCYCODE)) = 'PHP' THEN
        SET V_INTERMEDIATE_BALANCE = CAST(P_OUTSTANDINGBALANCE AS DECIMAL(31, 8));
    ELSEIF UPPER(TRIM(P_CURRENCYCODE)) = 'USD' THEN
        SET V_INTERMEDIATE_BALANCE = CAST(P_OUTSTANDINGBALANCE AS DECIMAL(31, 8)) * V_SPECIAL_RATE_USD;
    ELSE
        SET V_INTERMEDIATE_BALANCE = CAST(P_OUTSTANDINGBALANCE AS DECIMAL(31, 8)) * V_SPECIAL_RATE_THIRD * V_SPECIAL_RATE_USD;
    END IF;

    SET V_TOTAL_TLOSBAL = CAST(ROUND(V_INTERMEDIATE_BALANCE, 2) AS DECIMAL(19, 2));
    
    UPDATE TFSDB2S.LNCLST
		SET 
          CIFNO = P_CIFNUMBER,
          ORGLMT = P_ORIGINALAMOUNT,
          TOSBAL = P_OUTSTANDINGBALANCE,
          LORGAM = P_PHPAMOUNT,
          TLOSBAL = V_TOTAL_TLOSBAL,
          CURTYP = P_CURRENCYCODE,
          STADSC = UPPER(P_STATUSDESCRIPTION),
          AFCPNO = P_FACILITYREFERENCENUMBER
		WHERE ACCTNO = REPLACE(P_DOCUMENTNUMBER, '-', '');
		
	END IF;
END P1 @