--<ScriptOptions statementTerminator="@">

CREATE OR REPLACE PROCEDURE TFSDB2S.UPDATE_CICLS_RATES()
SPECIFIC UPDATE_CICLS_RATES
LANGUAGE SQL
P1: BEGIN

    UPDATE TFSDB2S.LNCLST
    SET ORGLMT_IRR =
        CASE WHEN LPAD(DATE, 6, 0) = TO_CHAR(NOW(), 'MMDDYY') THEN LORGAM
            WHEN CURTYP = 'PHP' THEN ORGLMT
            ELSE (ORGLMT * (VALUES TFSDB2S.GET_IRR_RATE(CURTYP)))
        END
        , TOSBAL_IRR =
        CASE WHEN LPAD(DATE, 6, 0) = TO_CHAR(NOW(), 'MMDDYY') THEN TLOSBAL
            WHEN CURTYP = 'PHP' THEN TOSBAL
            ELSE (TOSBAL * (VALUES TFSDB2S.GET_IRR_RATE(CURTYP)))
        END
    ;

    UPDATE TFSDB2S.LNCLST_CICLS
    SET ORGLMT_IRR =
        CASE WHEN LPAD(DATE, 6, 0) = TO_CHAR(NOW(), 'MMDDYY') THEN LORGAM
            WHEN CURTYP = 'PHP' THEN ORGLMT
            ELSE (ORGLMT * (VALUES TFSDB2S.GET_IRR_RATE(CURTYP)))
        END
        , TOSBAL_IRR =
        CASE WHEN LPAD(DATE, 6, 0) = TO_CHAR(NOW(), 'MMDDYY') THEN TLOSBAL
            WHEN CURTYP = 'PHP' THEN TOSBAL
            ELSE (TOSBAL * (VALUES TFSDB2S.GET_IRR_RATE(CURTYP)))
        END
    ;

    UPDATE TFSDB2S.LNTFINT
    SET 
    LORGAMT_IRR = 
        CASE WHEN LPAD(ORGDT6, 6, 0) = TO_CHAR(NOW(), 'MMDDYY') THEN LORGAMT
             WHEN CURTYP = 'PHP' THEN ORGAMT
             ELSE (ORGAMT * (VALUES TFSDB2S.GET_IRR_RATE(CURTYP)))
        END
    , LPMTAMT_IRR =
        CASE WHEN LPAD(ORGDT6, 6, 0) = TO_CHAR(NOW(), 'MMDDYY') THEN LPMTAMT
             WHEN CURTYP = 'PHP' THEN PMTAMT
             ELSE (PMTAMT * (VALUES TFSDB2S.GET_IRR_RATE(CURTYP)))
        END
    ;

    UPDATE TFSDB2S.LNTFINT_CICLS
    SET 
        LORGAMT_IRR = 
        CASE WHEN LPAD(ORGDT6, 6, 0) = TO_CHAR(NOW(), 'MMDDYY') THEN LORGAMT
            WHEN CURTYP = 'PHP' THEN ORGAMT
            ELSE (ORGAMT * (VALUES TFSDB2S.GET_IRR_RATE(CURTYP)))
        END
        , LPMTAMT_IRR =
        CASE WHEN LPAD(ORGDT6, 6, 0) = TO_CHAR(NOW(), 'MMDDYY') THEN LPMTAMT
            WHEN CURTYP = 'PHP' THEN PMTAMT
            ELSE (PMTAMT * (VALUES TFSDB2S.GET_IRR_RATE(CURTYP)))
        END
    ;
END P1 @