SELECT 
    			EFFECTIVEDATE, ACCOUNTINGCODE, BOOKCODE,ORIGINALCURRENCY,TS.DOCUMENTNUMBER,PRODUCTID,
     			ORIGINALAMOUNT,DESCRIPTION,CCBDBRANCHUNITCODE, DATECLOSED, PROCESSDATE, TOTALBALANCE 
  			FROM TFS.INT_ACCENTRYACTUAL GL
              INNER JOIN 
              	TFS.GL_ENTRY_TYPES GL_CODES ON 
             	GL_CODES.GLCODE = GL.ACCOUNTINGCODE
           	  INNER JOIN 
              	TFS.TRADESERVICE TS ON 
              	GL.TRADESERVICEID = TS.TRADESERVICEID
              INNER JOIN
              	TFS.LETTEROFCREDIT LC ON
              	LC.DOCUMENTNUMBER = TS.DOCUMENTNUMBER
              INNER JOIN 
              	(SELECT SUM(BALANCE) TOTALBALANCE, DOCUMENTNUMBER FROM TFS.DAILYBALANCE 
              	WHERE MONTH(BALANCE_DATE) = MONTH(CURRENT_TIMESTAMP) AND YEAR(BALANCE_DATE) = YEAR(CURRENT_TIMESTAMP)
              	GROUP BY DOCUMENTNUMBER) BALANCES
              	ON BALANCES.DOCUMENTNUMBER = TS.DOCUMENTNUMBER
              WHERE MONTH(GL.EFFECTIVEDATE) = MONTH(CURRENT_TIMESTAMP)
              AND YEAR(GL.EFFECTIVEDATE) = YEAR(CURRENT_TIMESTAMP) 
              AND GL_CODES.RECORDTYPE = 'INCOME';