package com.ucpb.tfs.report.dw.regen;

import com.ucpb.tfs.domain.product.DocumentNumber;
import com.ucpb.tfs.domain.product.enums.DCDocumentType;
import com.ucpb.tfs.domain.service.enumTypes.DocumentType;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * User: IPCVal
 */
public class DocumentAgainstAcceptanceAudit implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private DocumentNumber documentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REV_ID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Integer revId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTNUMBER
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getDocumentNumber() {
        return documentNumber.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTNUMBER
     *
     * @param documentNumber the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setDocumentNumber(DocumentNumber documentNumber) {
        this.documentNumber = documentNumber == null ? null : documentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REV_ID
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.REV_ID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Integer getRevId() {
        return revId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REV_ID
     *
     * @param revId the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.REV_ID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setRevId(Integer revId) {
        this.revId = revId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.TSNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String tsNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private DocumentType documentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANK
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String remittingBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REIMBURSINGBANK
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String reimbursingBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date processDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANKREFERENCENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String remittingBankReferenceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.CURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.AMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.OUTSTANDINGAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal outstandingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.DATEOFBLAIRWAYBILL
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date dateOfBlAirwayBill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.MATURITYDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date maturityDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCIFNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String importerCifNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.ORIGINALPORT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String originalPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCBCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String importerCbCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String importerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String importerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String senderToReceiverInformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String beneficiaryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String beneficiaryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.LASTTRANSACTION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String lastTransaction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.CANCELLEDDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date cancelledDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.SETTLEDDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date settledDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSINGUNITCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String processingUnitCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.TSNUMBER
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.TSNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getTsNumber() {
        return tsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.TSNUMBER
     *
     * @param tsNumber the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.TSNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setTsNumber(String tsNumber) {
        this.tsNumber = tsNumber == null ? null : tsNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTTYPE
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getDocumentType() {
        return documentType.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTTYPE
     *
     * @param documentType the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.DOCUMENTTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setDocumentType(DocumentType documentType) {
        this.documentType = documentType == null ? null : documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANK
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANK
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getRemittingBank() {
        return remittingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANK
     *
     * @param remittingBank the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANK
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setRemittingBank(String remittingBank) {
        this.remittingBank = remittingBank == null ? null : remittingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REIMBURSINGBANK
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.REIMBURSINGBANK
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getReimbursingBank() {
        return reimbursingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REIMBURSINGBANK
     *
     * @param reimbursingBank the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.REIMBURSINGBANK
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setReimbursingBank(String reimbursingBank) {
        this.reimbursingBank = reimbursingBank == null ? null : reimbursingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSDATE
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getProcessDate() {
        return processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSDATE
     *
     * @param processDate the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANKREFERENCENUMBER
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANKREFERENCENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getRemittingBankReferenceNumber() {
        return remittingBankReferenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANKREFERENCENUMBER
     *
     * @param remittingBankReferenceNumber the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.REMITTINGBANKREFERENCENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setRemittingBankReferenceNumber(String remittingBankReferenceNumber) {
        this.remittingBankReferenceNumber = remittingBankReferenceNumber == null ? null : remittingBankReferenceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.CURRENCY
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.CURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.CURRENCY
     *
     * @param currency the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.CURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.AMOUNT
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.AMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.AMOUNT
     *
     * @param amount the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.AMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.OUTSTANDINGAMOUNT
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.OUTSTANDINGAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getOutstandingAmount() {
        return outstandingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.OUTSTANDINGAMOUNT
     *
     * @param outstandingAmount the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.OUTSTANDINGAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setOutstandingAmount(BigDecimal outstandingAmount) {
        this.outstandingAmount = outstandingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.DATEOFBLAIRWAYBILL
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.DATEOFBLAIRWAYBILL
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getDateOfBlAirwayBill() {
        return dateOfBlAirwayBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.DATEOFBLAIRWAYBILL
     *
     * @param dateOfBlAirwayBill the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.DATEOFBLAIRWAYBILL
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setDateOfBlAirwayBill(Date dateOfBlAirwayBill) {
        this.dateOfBlAirwayBill = dateOfBlAirwayBill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.MATURITYDATE
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.MATURITYDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getMaturityDate() {
        return maturityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.MATURITYDATE
     *
     * @param maturityDate the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.MATURITYDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setMaturityDate(Date maturityDate) {
        this.maturityDate = maturityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCIFNUMBER
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCIFNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getImporterCifNumber() {
        return importerCifNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCIFNUMBER
     *
     * @param importerCifNumber the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCIFNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setImporterCifNumber(String importerCifNumber) {
        this.importerCifNumber = importerCifNumber == null ? null : importerCifNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.ORIGINALPORT
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.ORIGINALPORT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getOriginalPort() {
        return originalPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.ORIGINALPORT
     *
     * @param originalPort the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.ORIGINALPORT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setOriginalPort(String originalPort) {
        this.originalPort = originalPort == null ? null : originalPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCBCODE
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCBCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getImporterCbCode() {
        return importerCbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCBCODE
     *
     * @param importerCbCode the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERCBCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setImporterCbCode(String importerCbCode) {
        this.importerCbCode = importerCbCode == null ? null : importerCbCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERNAME
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getImporterName() {
        return importerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERNAME
     *
     * @param importerName the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setImporterName(String importerName) {
        this.importerName = importerName == null ? null : importerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERADDRESS
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getImporterAddress() {
        return importerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERADDRESS
     *
     * @param importerAddress the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.IMPORTERADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setImporterAddress(String importerAddress) {
        this.importerAddress = importerAddress == null ? null : importerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getSenderToReceiverInformation() {
        return senderToReceiverInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @param senderToReceiverInformation the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setSenderToReceiverInformation(String senderToReceiverInformation) {
        this.senderToReceiverInformation = senderToReceiverInformation == null ? null : senderToReceiverInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYNAME
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getBeneficiaryName() {
        return beneficiaryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYNAME
     *
     * @param beneficiaryName the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setBeneficiaryName(String beneficiaryName) {
        this.beneficiaryName = beneficiaryName == null ? null : beneficiaryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYADDRESS
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getBeneficiaryAddress() {
        return beneficiaryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYADDRESS
     *
     * @param beneficiaryAddress the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.BENEFICIARYADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setBeneficiaryAddress(String beneficiaryAddress) {
        this.beneficiaryAddress = beneficiaryAddress == null ? null : beneficiaryAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.LASTTRANSACTION
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.LASTTRANSACTION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getLastTransaction() {
        return lastTransaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.LASTTRANSACTION
     *
     * @param lastTransaction the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.LASTTRANSACTION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLastTransaction(String lastTransaction) {
        this.lastTransaction = lastTransaction == null ? null : lastTransaction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.CANCELLEDDATE
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.CANCELLEDDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getCancelledDate() {
        return cancelledDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.CANCELLEDDATE
     *
     * @param cancelledDate the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.CANCELLEDDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCancelledDate(Date cancelledDate) {
        this.cancelledDate = cancelledDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.SETTLEDDATE
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.SETTLEDDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getSettledDate() {
        return settledDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.SETTLEDDATE
     *
     * @param settledDate the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.SETTLEDDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setSettledDate(Date settledDate) {
        this.settledDate = settledDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSINGUNITCODE
     *
     * @return the value of DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSINGUNITCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getProcessingUnitCode() {
        return processingUnitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSINGUNITCODE
     *
     * @param processingUnitCode the value for DOCUMENTAGAINSTACCEPTANCE_AUDIT.PROCESSINGUNITCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setProcessingUnitCode(String processingUnitCode) {
        this.processingUnitCode = processingUnitCode == null ? null : processingUnitCode.trim();
    }
}
