package com.ucpb.tfs.report.dw.regen;

import com.ucpb.tfs.domain.product.DocumentNumber;
import com.ucpb.tfs.domain.product.enums.AccountType;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * User: IPCVal
 */

public class ExportBillsAudit implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.DOCUMENTNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private DocumentNumber documentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.REV_ID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Integer revId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.DOCUMENTNUMBER
     *
     * @return the value of EXPORTBILLS_AUDIT.DOCUMENTNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getDocumentNumber() {
        return documentNumber.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.DOCUMENTNUMBER
     *
     * @param documentNumber the value for EXPORTBILLS_AUDIT.DOCUMENTNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setDocumentNumber(DocumentNumber documentNumber) {
        this.documentNumber = documentNumber == null ? null : documentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.REV_ID
     *
     * @return the value of EXPORTBILLS_AUDIT.REV_ID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Integer getRevId() {
        return revId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.REV_ID
     *
     * @param revId the value for EXPORTBILLS_AUDIT.REV_ID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setRevId(Integer revId) {
        this.revId = revId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.EXPORTBILLTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String exportBillType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.EXPORTVIAPDDTSFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Short exportViaPddtsFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CWTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Short cwtFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.PAYMENTMODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String paymentMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.OUTSTANDINGAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal outstandingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.NEGOTIATIONNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String negotiationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.FACILITYTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String facilityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.FACILTIYID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String faciltiyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.BOOKINGCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String bookingCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LOANAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.INTERESTRATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal interestRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.INTERESTTERMCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String interestTermCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.INTERESTTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Long interestTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LOANTERMCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String loanTermCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LOANTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Long loanTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LOANMATURITYDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date loanMaturityDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.NUMBEROFFREEFLOATDAYS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Long numberOfFreeFloatDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.AGRIAGRATAGGING
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String agriAgraTagging;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.PAYMENTCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String paymentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.PNNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String pnNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.TRANSACTIONPOSTINGSTATUS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String transactionPostingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.ADVISENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String adviseNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LCNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String lcNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LCISSUEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date lcIssueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LCTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String lcType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LCTENOR
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String lcTenor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.USANCETERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String usanceTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LCCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String lcCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LCAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal lcAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.LCEXPIRYDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date lcExpiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.ISSUINGBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String issuingBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.ISSUINGBANKADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String issuingBankAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.REIMBURSINGBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String reimbursingBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.TENOR
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String tenor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.TENORTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Long tenorTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.NONLCTENOR
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String nonLcTenor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.NONLCTENORTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String nonLcTenorTerm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.DRAFTCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String draftCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.DRAFTAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal draftAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.DUEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date dueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.COLLECTINGBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String collectingBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.COLLECTINGBANKADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String collectingBankAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.INVOICENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String invoiceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.ADDITIONALAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal additionalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CHARGESCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String chargesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CHARGEAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal chargeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CHARGENARRATIVE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String chargeNarrative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String totalAmountClaimedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date totalAmountClaimedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMED
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal totalAmountClaimed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String totalAmountClaimedCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CORRESBANKFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String corresBankFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CORRESBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String corresBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CORRESBANKNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String corresBankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CORRESBANKACCOUNTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String corresBankAccountFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CORRESBANKACCOUNTCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String corresBankAccountCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CORRESBANKACCOUNTNAMEANDADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String corresBankAccountNameAndAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.ACCOUNTTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private AccountType accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.DEPOSITORYACCOUNTNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String depositoryAccountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.GLCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String glCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.CORRESBANKCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String corresBankcurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String senderToReceiverInformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.PROCESSDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date processDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.SETTLEMENTDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date settlementDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.PROCEEDSAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal proceedsAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.MTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Short mtFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.COUNTRYCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.SELLERNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String sellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.BUYERNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String buyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.BUYERADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String buyerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.REASONFORCANCELLATION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String reasonForCancellation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.PARTIALNEGO
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String partialNego;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.BPAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal bpAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.BPCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String bpCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.EXPORTERCBCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String exporterCbCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EXPORTBILLS_AUDIT.NEGOTIATIONDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date negotiationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.EXPORTBILLTYPE
     *
     * @return the value of EXPORTBILLS_AUDIT.EXPORTBILLTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getExportBillType() {
        return exportBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.EXPORTBILLTYPE
     *
     * @param exportBillType the value for EXPORTBILLS_AUDIT.EXPORTBILLTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setExportBillType(String exportBillType) {
        this.exportBillType = exportBillType == null ? null : exportBillType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.EXPORTVIAPDDTSFLAG
     *
     * @return the value of EXPORTBILLS_AUDIT.EXPORTVIAPDDTSFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Short getExportViaPddtsFlag() {
        return exportViaPddtsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.EXPORTVIAPDDTSFLAG
     *
     * @param exportViaPddtsFlag the value for EXPORTBILLS_AUDIT.EXPORTVIAPDDTSFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setExportViaPddtsFlag(Short exportViaPddtsFlag) {
        this.exportViaPddtsFlag = exportViaPddtsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CWTFLAG
     *
     * @return the value of EXPORTBILLS_AUDIT.CWTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Short getCwtFlag() {
        return cwtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CWTFLAG
     *
     * @param cwtFlag the value for EXPORTBILLS_AUDIT.CWTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCwtFlag(Short cwtFlag) {
        this.cwtFlag = cwtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.PAYMENTMODE
     *
     * @return the value of EXPORTBILLS_AUDIT.PAYMENTMODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getPaymentMode() {
        return paymentMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.PAYMENTMODE
     *
     * @param paymentMode the value for EXPORTBILLS_AUDIT.PAYMENTMODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode == null ? null : paymentMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.OUTSTANDINGAMOUNT
     *
     * @return the value of EXPORTBILLS_AUDIT.OUTSTANDINGAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getOutstandingAmount() {
        return outstandingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.OUTSTANDINGAMOUNT
     *
     * @param outstandingAmount the value for EXPORTBILLS_AUDIT.OUTSTANDINGAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setOutstandingAmount(BigDecimal outstandingAmount) {
        this.outstandingAmount = outstandingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.NEGOTIATIONNUMBER
     *
     * @return the value of EXPORTBILLS_AUDIT.NEGOTIATIONNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getNegotiationNumber() {
        return negotiationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.NEGOTIATIONNUMBER
     *
     * @param negotiationNumber the value for EXPORTBILLS_AUDIT.NEGOTIATIONNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setNegotiationNumber(String negotiationNumber) {
        this.negotiationNumber = negotiationNumber == null ? null : negotiationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.FACILITYTYPE
     *
     * @return the value of EXPORTBILLS_AUDIT.FACILITYTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getFacilityType() {
        return facilityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.FACILITYTYPE
     *
     * @param facilityType the value for EXPORTBILLS_AUDIT.FACILITYTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setFacilityType(String facilityType) {
        this.facilityType = facilityType == null ? null : facilityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.FACILTIYID
     *
     * @return the value of EXPORTBILLS_AUDIT.FACILTIYID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getFaciltiyId() {
        return faciltiyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.FACILTIYID
     *
     * @param faciltiyId the value for EXPORTBILLS_AUDIT.FACILTIYID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setFaciltiyId(String faciltiyId) {
        this.faciltiyId = faciltiyId == null ? null : faciltiyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.BOOKINGCURRENCY
     *
     * @return the value of EXPORTBILLS_AUDIT.BOOKINGCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getBookingCurrency() {
        return bookingCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.BOOKINGCURRENCY
     *
     * @param bookingCurrency the value for EXPORTBILLS_AUDIT.BOOKINGCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setBookingCurrency(String bookingCurrency) {
        this.bookingCurrency = bookingCurrency == null ? null : bookingCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LOANAMOUNT
     *
     * @return the value of EXPORTBILLS_AUDIT.LOANAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LOANAMOUNT
     *
     * @param loanAmount the value for EXPORTBILLS_AUDIT.LOANAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.INTERESTRATE
     *
     * @return the value of EXPORTBILLS_AUDIT.INTERESTRATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getInterestRate() {
        return interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.INTERESTRATE
     *
     * @param interestRate the value for EXPORTBILLS_AUDIT.INTERESTRATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setInterestRate(BigDecimal interestRate) {
        this.interestRate = interestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.INTERESTTERMCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.INTERESTTERMCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getInterestTermCode() {
        return interestTermCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.INTERESTTERMCODE
     *
     * @param interestTermCode the value for EXPORTBILLS_AUDIT.INTERESTTERMCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setInterestTermCode(String interestTermCode) {
        this.interestTermCode = interestTermCode == null ? null : interestTermCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.INTERESTTERM
     *
     * @return the value of EXPORTBILLS_AUDIT.INTERESTTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Long getInterestTerm() {
        return interestTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.INTERESTTERM
     *
     * @param interestTerm the value for EXPORTBILLS_AUDIT.INTERESTTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setInterestTerm(Long interestTerm) {
        this.interestTerm = interestTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LOANTERMCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.LOANTERMCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getLoanTermCode() {
        return loanTermCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LOANTERMCODE
     *
     * @param loanTermCode the value for EXPORTBILLS_AUDIT.LOANTERMCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLoanTermCode(String loanTermCode) {
        this.loanTermCode = loanTermCode == null ? null : loanTermCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LOANTERM
     *
     * @return the value of EXPORTBILLS_AUDIT.LOANTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Long getLoanTerm() {
        return loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LOANTERM
     *
     * @param loanTerm the value for EXPORTBILLS_AUDIT.LOANTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLoanTerm(Long loanTerm) {
        this.loanTerm = loanTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LOANMATURITYDATE
     *
     * @return the value of EXPORTBILLS_AUDIT.LOANMATURITYDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getLoanMaturityDate() {
        return loanMaturityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LOANMATURITYDATE
     *
     * @param loanMaturityDate the value for EXPORTBILLS_AUDIT.LOANMATURITYDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLoanMaturityDate(Date loanMaturityDate) {
        this.loanMaturityDate = loanMaturityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.NUMBEROFFREEFLOATDAYS
     *
     * @return the value of EXPORTBILLS_AUDIT.NUMBEROFFREEFLOATDAYS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Long getNumberOfFreeFloatDays() {
        return numberOfFreeFloatDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.NUMBEROFFREEFLOATDAYS
     *
     * @param numberOfFreeFloatDays the value for EXPORTBILLS_AUDIT.NUMBEROFFREEFLOATDAYS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setNumberOfFreeFloatDays(Long numberOfFreeFloatDays) {
        this.numberOfFreeFloatDays = numberOfFreeFloatDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.AGRIAGRATAGGING
     *
     * @return the value of EXPORTBILLS_AUDIT.AGRIAGRATAGGING
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getAgriAgraTagging() {
        return agriAgraTagging;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.AGRIAGRATAGGING
     *
     * @param agriAgraTagging the value for EXPORTBILLS_AUDIT.AGRIAGRATAGGING
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setAgriAgraTagging(String agriAgraTagging) {
        this.agriAgraTagging = agriAgraTagging == null ? null : agriAgraTagging.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.PAYMENTCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.PAYMENTCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getPaymentCode() {
        return paymentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.PAYMENTCODE
     *
     * @param paymentCode the value for EXPORTBILLS_AUDIT.PAYMENTCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setPaymentCode(String paymentCode) {
        this.paymentCode = paymentCode == null ? null : paymentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.PNNUMBER
     *
     * @return the value of EXPORTBILLS_AUDIT.PNNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getPnNumber() {
        return pnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.PNNUMBER
     *
     * @param pnNumber the value for EXPORTBILLS_AUDIT.PNNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setPnNumber(String pnNumber) {
        this.pnNumber = pnNumber == null ? null : pnNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.TRANSACTIONPOSTINGSTATUS
     *
     * @return the value of EXPORTBILLS_AUDIT.TRANSACTIONPOSTINGSTATUS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getTransactionPostingStatus() {
        return transactionPostingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.TRANSACTIONPOSTINGSTATUS
     *
     * @param transactionPostingStatus the value for EXPORTBILLS_AUDIT.TRANSACTIONPOSTINGSTATUS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setTransactionPostingStatus(String transactionPostingStatus) {
        this.transactionPostingStatus = transactionPostingStatus == null ? null : transactionPostingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.ADVISENUMBER
     *
     * @return the value of EXPORTBILLS_AUDIT.ADVISENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getAdviseNumber() {
        return adviseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.ADVISENUMBER
     *
     * @param adviseNumber the value for EXPORTBILLS_AUDIT.ADVISENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setAdviseNumber(String adviseNumber) {
        this.adviseNumber = adviseNumber == null ? null : adviseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LCNUMBER
     *
     * @return the value of EXPORTBILLS_AUDIT.LCNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getLcNumber() {
        return lcNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LCNUMBER
     *
     * @param lcNumber the value for EXPORTBILLS_AUDIT.LCNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLcNumber(String lcNumber) {
        this.lcNumber = lcNumber == null ? null : lcNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LCISSUEDATE
     *
     * @return the value of EXPORTBILLS_AUDIT.LCISSUEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getLcIssueDate() {
        return lcIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LCISSUEDATE
     *
     * @param lcIssueDate the value for EXPORTBILLS_AUDIT.LCISSUEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLcIssueDate(Date lcIssueDate) {
        this.lcIssueDate = lcIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LCTYPE
     *
     * @return the value of EXPORTBILLS_AUDIT.LCTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getLcType() {
        return lcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LCTYPE
     *
     * @param lcType the value for EXPORTBILLS_AUDIT.LCTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLcType(String lcType) {
        this.lcType = lcType == null ? null : lcType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LCTENOR
     *
     * @return the value of EXPORTBILLS_AUDIT.LCTENOR
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getLcTenor() {
        return lcTenor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LCTENOR
     *
     * @param lcTenor the value for EXPORTBILLS_AUDIT.LCTENOR
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLcTenor(String lcTenor) {
        this.lcTenor = lcTenor == null ? null : lcTenor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.USANCETERM
     *
     * @return the value of EXPORTBILLS_AUDIT.USANCETERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getUsanceTerm() {
        return usanceTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.USANCETERM
     *
     * @param usanceTerm the value for EXPORTBILLS_AUDIT.USANCETERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setUsanceTerm(String usanceTerm) {
        this.usanceTerm = usanceTerm == null ? null : usanceTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LCCURRENCY
     *
     * @return the value of EXPORTBILLS_AUDIT.LCCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getLcCurrency() {
        return lcCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LCCURRENCY
     *
     * @param lcCurrency the value for EXPORTBILLS_AUDIT.LCCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLcCurrency(String lcCurrency) {
        this.lcCurrency = lcCurrency == null ? null : lcCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LCAMOUNT
     *
     * @return the value of EXPORTBILLS_AUDIT.LCAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getLcAmount() {
        return lcAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LCAMOUNT
     *
     * @param lcAmount the value for EXPORTBILLS_AUDIT.LCAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLcAmount(BigDecimal lcAmount) {
        this.lcAmount = lcAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.LCEXPIRYDATE
     *
     * @return the value of EXPORTBILLS_AUDIT.LCEXPIRYDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getLcExpiryDate() {
        return lcExpiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.LCEXPIRYDATE
     *
     * @param lcExpiryDate the value for EXPORTBILLS_AUDIT.LCEXPIRYDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setLcExpiryDate(Date lcExpiryDate) {
        this.lcExpiryDate = lcExpiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.ISSUINGBANKCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.ISSUINGBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getIssuingBankCode() {
        return issuingBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.ISSUINGBANKCODE
     *
     * @param issuingBankCode the value for EXPORTBILLS_AUDIT.ISSUINGBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setIssuingBankCode(String issuingBankCode) {
        this.issuingBankCode = issuingBankCode == null ? null : issuingBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.ISSUINGBANKADDRESS
     *
     * @return the value of EXPORTBILLS_AUDIT.ISSUINGBANKADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getIssuingBankAddress() {
        return issuingBankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.ISSUINGBANKADDRESS
     *
     * @param issuingBankAddress the value for EXPORTBILLS_AUDIT.ISSUINGBANKADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setIssuingBankAddress(String issuingBankAddress) {
        this.issuingBankAddress = issuingBankAddress == null ? null : issuingBankAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.REIMBURSINGBANKCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.REIMBURSINGBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getReimbursingBankCode() {
        return reimbursingBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.REIMBURSINGBANKCODE
     *
     * @param reimbursingBankCode the value for EXPORTBILLS_AUDIT.REIMBURSINGBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setReimbursingBankCode(String reimbursingBankCode) {
        this.reimbursingBankCode = reimbursingBankCode == null ? null : reimbursingBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.TENOR
     *
     * @return the value of EXPORTBILLS_AUDIT.TENOR
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getTenor() {
        return tenor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.TENOR
     *
     * @param tenor the value for EXPORTBILLS_AUDIT.TENOR
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setTenor(String tenor) {
        this.tenor = tenor == null ? null : tenor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.TENORTERM
     *
     * @return the value of EXPORTBILLS_AUDIT.TENORTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Long getTenorTerm() {
        return tenorTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.TENORTERM
     *
     * @param tenorTerm the value for EXPORTBILLS_AUDIT.TENORTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setTenorTerm(Long tenorTerm) {
        this.tenorTerm = tenorTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.NONLCTENOR
     *
     * @return the value of EXPORTBILLS_AUDIT.NONLCTENOR
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getNonLcTenor() {
        return nonLcTenor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.NONLCTENOR
     *
     * @param nonLcTenor the value for EXPORTBILLS_AUDIT.NONLCTENOR
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setNonLcTenor(String nonLcTenor) {
        this.nonLcTenor = nonLcTenor == null ? null : nonLcTenor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.NONLCTENORTERM
     *
     * @return the value of EXPORTBILLS_AUDIT.NONLCTENORTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getNonLcTenorTerm() {
        return nonLcTenorTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.NONLCTENORTERM
     *
     * @param nonLcTenorTerm the value for EXPORTBILLS_AUDIT.NONLCTENORTERM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setNonLcTenorTerm(String nonLcTenorTerm) {
        this.nonLcTenorTerm = nonLcTenorTerm == null ? null : nonLcTenorTerm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.DRAFTCURRENCY
     *
     * @return the value of EXPORTBILLS_AUDIT.DRAFTCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getDraftCurrency() {
        return draftCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.DRAFTCURRENCY
     *
     * @param draftCurrency the value for EXPORTBILLS_AUDIT.DRAFTCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setDraftCurrency(String draftCurrency) {
        this.draftCurrency = draftCurrency == null ? null : draftCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.DRAFTAMOUNT
     *
     * @return the value of EXPORTBILLS_AUDIT.DRAFTAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getDraftAmount() {
        return draftAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.DRAFTAMOUNT
     *
     * @param draftAmount the value for EXPORTBILLS_AUDIT.DRAFTAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setDraftAmount(BigDecimal draftAmount) {
        this.draftAmount = draftAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.DUEDATE
     *
     * @return the value of EXPORTBILLS_AUDIT.DUEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.DUEDATE
     *
     * @param dueDate the value for EXPORTBILLS_AUDIT.DUEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.COLLECTINGBANKCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.COLLECTINGBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCollectingBankCode() {
        return collectingBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.COLLECTINGBANKCODE
     *
     * @param collectingBankCode the value for EXPORTBILLS_AUDIT.COLLECTINGBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCollectingBankCode(String collectingBankCode) {
        this.collectingBankCode = collectingBankCode == null ? null : collectingBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.COLLECTINGBANKADDRESS
     *
     * @return the value of EXPORTBILLS_AUDIT.COLLECTINGBANKADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCollectingBankAddress() {
        return collectingBankAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.COLLECTINGBANKADDRESS
     *
     * @param collectingBankAddress the value for EXPORTBILLS_AUDIT.COLLECTINGBANKADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCollectingBankAddress(String collectingBankAddress) {
        this.collectingBankAddress = collectingBankAddress == null ? null : collectingBankAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.INVOICENUMBER
     *
     * @return the value of EXPORTBILLS_AUDIT.INVOICENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.INVOICENUMBER
     *
     * @param invoiceNumber the value for EXPORTBILLS_AUDIT.INVOICENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber == null ? null : invoiceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.ADDITIONALAMOUNT
     *
     * @return the value of EXPORTBILLS_AUDIT.ADDITIONALAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getAdditionalAmount() {
        return additionalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.ADDITIONALAMOUNT
     *
     * @param additionalAmount the value for EXPORTBILLS_AUDIT.ADDITIONALAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setAdditionalAmount(BigDecimal additionalAmount) {
        this.additionalAmount = additionalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CHARGESCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.CHARGESCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getChargesCode() {
        return chargesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CHARGESCODE
     *
     * @param chargesCode the value for EXPORTBILLS_AUDIT.CHARGESCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setChargesCode(String chargesCode) {
        this.chargesCode = chargesCode == null ? null : chargesCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CHARGEAMOUNT
     *
     * @return the value of EXPORTBILLS_AUDIT.CHARGEAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getChargeAmount() {
        return chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CHARGEAMOUNT
     *
     * @param chargeAmount the value for EXPORTBILLS_AUDIT.CHARGEAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setChargeAmount(BigDecimal chargeAmount) {
        this.chargeAmount = chargeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CHARGENARRATIVE
     *
     * @return the value of EXPORTBILLS_AUDIT.CHARGENARRATIVE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getChargeNarrative() {
        return chargeNarrative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CHARGENARRATIVE
     *
     * @param chargeNarrative the value for EXPORTBILLS_AUDIT.CHARGENARRATIVE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setChargeNarrative(String chargeNarrative) {
        this.chargeNarrative = chargeNarrative == null ? null : chargeNarrative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDFLAG
     *
     * @return the value of EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getTotalAmountClaimedFlag() {
        return totalAmountClaimedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDFLAG
     *
     * @param totalAmountClaimedFlag the value for EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setTotalAmountClaimedFlag(String totalAmountClaimedFlag) {
        this.totalAmountClaimedFlag = totalAmountClaimedFlag == null ? null : totalAmountClaimedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDDATE
     *
     * @return the value of EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getTotalAmountClaimedDate() {
        return totalAmountClaimedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDDATE
     *
     * @param totalAmountClaimedDate the value for EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setTotalAmountClaimedDate(Date totalAmountClaimedDate) {
        this.totalAmountClaimedDate = totalAmountClaimedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMED
     *
     * @return the value of EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMED
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getTotalAmountClaimed() {
        return totalAmountClaimed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMED
     *
     * @param totalAmountClaimed the value for EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMED
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setTotalAmountClaimed(BigDecimal totalAmountClaimed) {
        this.totalAmountClaimed = totalAmountClaimed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDCURRENCY
     *
     * @return the value of EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getTotalAmountClaimedCurrency() {
        return totalAmountClaimedCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDCURRENCY
     *
     * @param totalAmountClaimedCurrency the value for EXPORTBILLS_AUDIT.TOTALAMOUNTCLAIMEDCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setTotalAmountClaimedCurrency(String totalAmountClaimedCurrency) {
        this.totalAmountClaimedCurrency = totalAmountClaimedCurrency == null ? null : totalAmountClaimedCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CORRESBANKFLAG
     *
     * @return the value of EXPORTBILLS_AUDIT.CORRESBANKFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCorresBankFlag() {
        return corresBankFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CORRESBANKFLAG
     *
     * @param corresBankFlag the value for EXPORTBILLS_AUDIT.CORRESBANKFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCorresBankFlag(String corresBankFlag) {
        this.corresBankFlag = corresBankFlag == null ? null : corresBankFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CORRESBANKCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.CORRESBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCorresBankCode() {
        return corresBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CORRESBANKCODE
     *
     * @param corresBankCode the value for EXPORTBILLS_AUDIT.CORRESBANKCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCorresBankCode(String corresBankCode) {
        this.corresBankCode = corresBankCode == null ? null : corresBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CORRESBANKNAME
     *
     * @return the value of EXPORTBILLS_AUDIT.CORRESBANKNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCorresBankName() {
        return corresBankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CORRESBANKNAME
     *
     * @param corresBankName the value for EXPORTBILLS_AUDIT.CORRESBANKNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCorresBankName(String corresBankName) {
        this.corresBankName = corresBankName == null ? null : corresBankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CORRESBANKACCOUNTFLAG
     *
     * @return the value of EXPORTBILLS_AUDIT.CORRESBANKACCOUNTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCorresBankAccountFlag() {
        return corresBankAccountFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CORRESBANKACCOUNTFLAG
     *
     * @param corresBankAccountFlag the value for EXPORTBILLS_AUDIT.CORRESBANKACCOUNTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCorresBankAccountFlag(String corresBankAccountFlag) {
        this.corresBankAccountFlag = corresBankAccountFlag == null ? null : corresBankAccountFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CORRESBANKACCOUNTCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.CORRESBANKACCOUNTCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCorresBankAccountCode() {
        return corresBankAccountCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CORRESBANKACCOUNTCODE
     *
     * @param corresBankAccountCode the value for EXPORTBILLS_AUDIT.CORRESBANKACCOUNTCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCorresBankAccountCode(String corresBankAccountCode) {
        this.corresBankAccountCode = corresBankAccountCode == null ? null : corresBankAccountCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CORRESBANKACCOUNTNAMEANDADDRESS
     *
     * @return the value of EXPORTBILLS_AUDIT.CORRESBANKACCOUNTNAMEANDADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCorresBankAccountNameAndAddress() {
        return corresBankAccountNameAndAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CORRESBANKACCOUNTNAMEANDADDRESS
     *
     * @param corresBankAccountNameAndAddress the value for EXPORTBILLS_AUDIT.CORRESBANKACCOUNTNAMEANDADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCorresBankAccountNameAndAddress(String corresBankAccountNameAndAddress) {
        this.corresBankAccountNameAndAddress = corresBankAccountNameAndAddress == null ? null : corresBankAccountNameAndAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.ACCOUNTTYPE
     *
     * @return the value of EXPORTBILLS_AUDIT.ACCOUNTTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getAccountType() {
        if (this.accountType != null) {
            return accountType.toString();
        } else {
            return null;
        }
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.ACCOUNTTYPE
     *
     * @param accountType the value for EXPORTBILLS_AUDIT.ACCOUNTTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setAccountType(AccountType accountType) {
        this.accountType = accountType == null ? null : accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.DEPOSITORYACCOUNTNUMBER
     *
     * @return the value of EXPORTBILLS_AUDIT.DEPOSITORYACCOUNTNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getDepositoryAccountNumber() {
        return depositoryAccountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.DEPOSITORYACCOUNTNUMBER
     *
     * @param depositoryAccountNumber the value for EXPORTBILLS_AUDIT.DEPOSITORYACCOUNTNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setDepositoryAccountNumber(String depositoryAccountNumber) {
        this.depositoryAccountNumber = depositoryAccountNumber == null ? null : depositoryAccountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.GLCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.GLCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getGlCode() {
        return glCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.GLCODE
     *
     * @param glCode the value for EXPORTBILLS_AUDIT.GLCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setGlCode(String glCode) {
        this.glCode = glCode == null ? null : glCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.CORRESBANKCURRENCY
     *
     * @return the value of EXPORTBILLS_AUDIT.CORRESBANKCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCorresBankcurrency() {
        return corresBankcurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.CORRESBANKCURRENCY
     *
     * @param corresBankcurrency the value for EXPORTBILLS_AUDIT.CORRESBANKCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCorresBankcurrency(String corresBankcurrency) {
        this.corresBankcurrency = corresBankcurrency == null ? null : corresBankcurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @return the value of EXPORTBILLS_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getSenderToReceiverInformation() {
        return senderToReceiverInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @param senderToReceiverInformation the value for EXPORTBILLS_AUDIT.SENDERTORECEIVERINFORMATION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setSenderToReceiverInformation(String senderToReceiverInformation) {
        this.senderToReceiverInformation = senderToReceiverInformation == null ? null : senderToReceiverInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.PROCESSDATE
     *
     * @return the value of EXPORTBILLS_AUDIT.PROCESSDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getProcessDate() {
        return processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.PROCESSDATE
     *
     * @param processDate the value for EXPORTBILLS_AUDIT.PROCESSDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.SETTLEMENTDATE
     *
     * @return the value of EXPORTBILLS_AUDIT.SETTLEMENTDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getSettlementDate() {
        return settlementDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.SETTLEMENTDATE
     *
     * @param settlementDate the value for EXPORTBILLS_AUDIT.SETTLEMENTDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setSettlementDate(Date settlementDate) {
        this.settlementDate = settlementDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.PROCEEDSAMOUNT
     *
     * @return the value of EXPORTBILLS_AUDIT.PROCEEDSAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getProceedsAmount() {
        return proceedsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.PROCEEDSAMOUNT
     *
     * @param proceedsAmount the value for EXPORTBILLS_AUDIT.PROCEEDSAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setProceedsAmount(BigDecimal proceedsAmount) {
        this.proceedsAmount = proceedsAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.MTFLAG
     *
     * @return the value of EXPORTBILLS_AUDIT.MTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Short getMtFlag() {
        return mtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.MTFLAG
     *
     * @param mtFlag the value for EXPORTBILLS_AUDIT.MTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setMtFlag(Short mtFlag) {
        this.mtFlag = mtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.COUNTRYCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.COUNTRYCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.COUNTRYCODE
     *
     * @param countryCode the value for EXPORTBILLS_AUDIT.COUNTRYCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.SELLERNAME
     *
     * @return the value of EXPORTBILLS_AUDIT.SELLERNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getSellerName() {
        return sellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.SELLERNAME
     *
     * @param sellerName the value for EXPORTBILLS_AUDIT.SELLERNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setSellerName(String sellerName) {
        this.sellerName = sellerName == null ? null : sellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.BUYERNAME
     *
     * @return the value of EXPORTBILLS_AUDIT.BUYERNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getBuyerName() {
        return buyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.BUYERNAME
     *
     * @param buyerName the value for EXPORTBILLS_AUDIT.BUYERNAME
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName == null ? null : buyerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.BUYERADDRESS
     *
     * @return the value of EXPORTBILLS_AUDIT.BUYERADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getBuyerAddress() {
        return buyerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.BUYERADDRESS
     *
     * @param buyerAddress the value for EXPORTBILLS_AUDIT.BUYERADDRESS
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setBuyerAddress(String buyerAddress) {
        this.buyerAddress = buyerAddress == null ? null : buyerAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.REASONFORCANCELLATION
     *
     * @return the value of EXPORTBILLS_AUDIT.REASONFORCANCELLATION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getReasonForCancellation() {
        return reasonForCancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.REASONFORCANCELLATION
     *
     * @param reasonForCancellation the value for EXPORTBILLS_AUDIT.REASONFORCANCELLATION
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setReasonForCancellation(String reasonForCancellation) {
        this.reasonForCancellation = reasonForCancellation == null ? null : reasonForCancellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.PARTIALNEGO
     *
     * @return the value of EXPORTBILLS_AUDIT.PARTIALNEGO
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getPartialNego() {
        return partialNego;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.PARTIALNEGO
     *
     * @param partialNego the value for EXPORTBILLS_AUDIT.PARTIALNEGO
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setPartialNego(String partialNego) {
        this.partialNego = partialNego == null ? null : partialNego.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.BPAMOUNT
     *
     * @return the value of EXPORTBILLS_AUDIT.BPAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getBpAmount() {
        return bpAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.BPAMOUNT
     *
     * @param bpAmount the value for EXPORTBILLS_AUDIT.BPAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setBpAmount(BigDecimal bpAmount) {
        this.bpAmount = bpAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.BPCURRENCY
     *
     * @return the value of EXPORTBILLS_AUDIT.BPCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getBpCurrency() {
        return bpCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.BPCURRENCY
     *
     * @param bpCurrency the value for EXPORTBILLS_AUDIT.BPCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setBpCurrency(String bpCurrency) {
        this.bpCurrency = bpCurrency == null ? null : bpCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.EXPORTERCBCODE
     *
     * @return the value of EXPORTBILLS_AUDIT.EXPORTERCBCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getExporterCbCode() {
        return exporterCbCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.EXPORTERCBCODE
     *
     * @param exporterCbCode the value for EXPORTBILLS_AUDIT.EXPORTERCBCODE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setExporterCbCode(String exporterCbCode) {
        this.exporterCbCode = exporterCbCode == null ? null : exporterCbCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EXPORTBILLS_AUDIT.NEGOTIATIONDATE
     *
     * @return the value of EXPORTBILLS_AUDIT.NEGOTIATIONDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getNegotiationDate() {
        return negotiationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EXPORTBILLS_AUDIT.NEGOTIATIONDATE
     *
     * @param negotiationDate the value for EXPORTBILLS_AUDIT.NEGOTIATIONDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setNegotiationDate(Date negotiationDate) {
        this.negotiationDate = negotiationDate;
    }
}
