package com.ucpb.tfs.report.dw.regen;

import com.ucpb.tfs.domain.product.DocumentNumber;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * User: IPCVal
 */
public class IndemnityAudit implements Serializable {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.INDEMNITYNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private DocumentNumber indemnityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.REV_ID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Integer revId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.INDEMNITYNUMBER
     *
     * @return the value of INDEMNITY_AUDIT.INDEMNITYNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getIndemnityNumber() {
        return indemnityNumber.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.INDEMNITYNUMBER
     *
     * @param indemnityNumber the value for INDEMNITY_AUDIT.INDEMNITYNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setIndemnityNumber(DocumentNumber indemnityNumber) {
        this.indemnityNumber = indemnityNumber == null ? null : indemnityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.REV_ID
     *
     * @return the value of INDEMNITY_AUDIT.REV_ID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Integer getRevId() {
        return revId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.REV_ID
     *
     * @param revId the value for INDEMNITY_AUDIT.REV_ID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setRevId(Integer revId) {
        this.revId = revId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.INDEMNITYTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String indemnityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.REFERENCENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String referenceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.TRANSPORTMEDIUM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String transportMedium;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.SHIPMENTSEQUENCENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Integer shipmentSequenceNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.SHIPMENTCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String shipmentCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.SHIPMENTAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private BigDecimal shipmentAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.INDEMNITYISSUEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date indemnityIssueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.CWTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Short cwtFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.BLAIRWAYBILLNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String blAirwayBillNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.PROCESSDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date processDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.BLPRESENTED
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String blPresented;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.FACILITYID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private String facilityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.CANCELLATIONDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date cancellationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INDEMNITY_AUDIT.DOCUMENTRELEASEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    private Date documentReleaseDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.INDEMNITYTYPE
     *
     * @return the value of INDEMNITY_AUDIT.INDEMNITYTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getIndemnityType() {
        return indemnityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.INDEMNITYTYPE
     *
     * @param indemnityType the value for INDEMNITY_AUDIT.INDEMNITYTYPE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setIndemnityType(String indemnityType) {
        this.indemnityType = indemnityType == null ? null : indemnityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.REFERENCENUMBER
     *
     * @return the value of INDEMNITY_AUDIT.REFERENCENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.REFERENCENUMBER
     *
     * @param referenceNumber the value for INDEMNITY_AUDIT.REFERENCENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setReferenceNumber(String referenceNumber) {
        this.referenceNumber = referenceNumber == null ? null : referenceNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.TRANSPORTMEDIUM
     *
     * @return the value of INDEMNITY_AUDIT.TRANSPORTMEDIUM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getTransportMedium() {
        return transportMedium;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.TRANSPORTMEDIUM
     *
     * @param transportMedium the value for INDEMNITY_AUDIT.TRANSPORTMEDIUM
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setTransportMedium(String transportMedium) {
        this.transportMedium = transportMedium == null ? null : transportMedium.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.SHIPMENTSEQUENCENUMBER
     *
     * @return the value of INDEMNITY_AUDIT.SHIPMENTSEQUENCENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Integer getShipmentSequenceNumber() {
        return shipmentSequenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.SHIPMENTSEQUENCENUMBER
     *
     * @param shipmentSequenceNumber the value for INDEMNITY_AUDIT.SHIPMENTSEQUENCENUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setShipmentSequenceNumber(Integer shipmentSequenceNumber) {
        this.shipmentSequenceNumber = shipmentSequenceNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.SHIPMENTCURRENCY
     *
     * @return the value of INDEMNITY_AUDIT.SHIPMENTCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getShipmentCurrency() {
        return shipmentCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.SHIPMENTCURRENCY
     *
     * @param shipmentCurrency the value for INDEMNITY_AUDIT.SHIPMENTCURRENCY
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setShipmentCurrency(String shipmentCurrency) {
        this.shipmentCurrency = shipmentCurrency == null ? null : shipmentCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.SHIPMENTAMOUNT
     *
     * @return the value of INDEMNITY_AUDIT.SHIPMENTAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public BigDecimal getShipmentAmount() {
        return shipmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.SHIPMENTAMOUNT
     *
     * @param shipmentAmount the value for INDEMNITY_AUDIT.SHIPMENTAMOUNT
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setShipmentAmount(BigDecimal shipmentAmount) {
        this.shipmentAmount = shipmentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.INDEMNITYISSUEDATE
     *
     * @return the value of INDEMNITY_AUDIT.INDEMNITYISSUEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getIndemnityIssueDate() {
        return indemnityIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.INDEMNITYISSUEDATE
     *
     * @param indemnityIssueDate the value for INDEMNITY_AUDIT.INDEMNITYISSUEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setIndemnityIssueDate(Date indemnityIssueDate) {
        this.indemnityIssueDate = indemnityIssueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.CWTFLAG
     *
     * @return the value of INDEMNITY_AUDIT.CWTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Short getCwtFlag() {
        return cwtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.CWTFLAG
     *
     * @param cwtFlag the value for INDEMNITY_AUDIT.CWTFLAG
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCwtFlag(Short cwtFlag) {
        this.cwtFlag = cwtFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.BLAIRWAYBILLNUMBER
     *
     * @return the value of INDEMNITY_AUDIT.BLAIRWAYBILLNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getBlAirwayBillNumber() {
        return blAirwayBillNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.BLAIRWAYBILLNUMBER
     *
     * @param blAirwayBillNumber the value for INDEMNITY_AUDIT.BLAIRWAYBILLNUMBER
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setBlAirwayBillNumber(String blAirwayBillNumber) {
        this.blAirwayBillNumber = blAirwayBillNumber == null ? null : blAirwayBillNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.PROCESSDATE
     *
     * @return the value of INDEMNITY_AUDIT.PROCESSDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getProcessDate() {
        return processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.PROCESSDATE
     *
     * @param processDate the value for INDEMNITY_AUDIT.PROCESSDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.BLPRESENTED
     *
     * @return the value of INDEMNITY_AUDIT.BLPRESENTED
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getBlPresented() {
        return blPresented;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.BLPRESENTED
     *
     * @param blPresented the value for INDEMNITY_AUDIT.BLPRESENTED
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setBlPresented(String blPresented) {
        this.blPresented = blPresented == null ? null : blPresented.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.FACILITYID
     *
     * @return the value of INDEMNITY_AUDIT.FACILITYID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public String getFacilityId() {
        return facilityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.FACILITYID
     *
     * @param facilityId the value for INDEMNITY_AUDIT.FACILITYID
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setFacilityId(String facilityId) {
        this.facilityId = facilityId == null ? null : facilityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.CANCELLATIONDATE
     *
     * @return the value of INDEMNITY_AUDIT.CANCELLATIONDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getCancellationDate() {
        return cancellationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.CANCELLATIONDATE
     *
     * @param cancellationDate the value for INDEMNITY_AUDIT.CANCELLATIONDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setCancellationDate(Date cancellationDate) {
        this.cancellationDate = cancellationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INDEMNITY_AUDIT.DOCUMENTRELEASEDATE
     *
     * @return the value of INDEMNITY_AUDIT.DOCUMENTRELEASEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public Date getDocumentReleaseDate() {
        return documentReleaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INDEMNITY_AUDIT.DOCUMENTRELEASEDATE
     *
     * @param documentReleaseDate the value for INDEMNITY_AUDIT.DOCUMENTRELEASEDATE
     *
     * @mbggenerated Sun Mar 30 00:40:00 CST 2014
     */
    public void setDocumentReleaseDate(Date documentReleaseDate) {
        this.documentReleaseDate = documentReleaseDate;
    }
}
